# -*- coding: utf-8 -*-
"""Paradigmi-oro LATINI: la generazione deve contenere le forme canoniche."""
import sys
sys.stdout.reconfigure(encoding='utf-8')
sys.path.insert(0, '_build')
from gen_latin_forms import main

gen = main(write=False)
fail = 0
def T(form, lemma, frag, note=''):
    global fail
    hits = gen.get(form, [])
    ok = any(l == lemma and frag in p for l, p in hits)
    if ok: print(f'OK   {form} → {lemma} · {frag}')
    else:
        fail += 1
        got = [f'{l}·{p[:40]}' for l, p in hits[:3]]
        print(f'FAIL {form} → atteso {lemma}/{frag} · trovato: {got} {note}')

print('— 1ª–5ª declinazione —')
T('rosae', 'rosa', 'gen./dat. sg.')
T('rosarum', 'rosa', 'gen. pl.')
T('dominorum', 'dominus', 'gen. pl.')
T('domine', 'dominus', 'voc. sg.')
T('belli', 'bellum', 'gen. sg.')
T('bella', 'bellum', 'nom./acc. pl.')
T('regis', 'rex', 'gen. sg.')
T('regum', 'rex', 'gen. pl.')
T('urbium', 'urbs', 'gen. pl.', '(tema in -i!)')
T('hostium', 'hostis', 'gen. pl.', '(parisillabo)')
T('corporis', 'corpus', 'gen. sg.')
T('corpora', 'corpus', 'nom./acc. pl.')
T('manui', 'manus', 'dat. sg.')
T('manuum', 'manus', 'gen. pl.')
T('manibus', 'manus', 'dat./abl. pl.')
T('rei', 'res', 'gen./dat. sg.')
T('rebus', 'res', 'dat./abl. pl.')
T('pueri', 'puer', 'gen. sg.')
T('agri', 'ager', 'gen. sg.')
print('— amo (1ª coniugazione, sistema completo) —')
T('amat', 'amo', 'pres. ind. att. 3ª sg.')
T('amabat', 'amo', 'impf. ind. att. 3ª sg.')
T('amabit', 'amo', 'fut. ind. att. 3ª sg.')
T('amet', 'amo', 'pres. cong. att. 3ª sg.')
T('amaret', 'amo', 'impf. cong. att. 3ª sg.')
T('amavit', 'amo', 'pf. ind. att. 3ª sg.')
T('amaverat', 'amo', 'ppf. ind. att. 3ª sg.')
T('amavisset', 'amo', 'ppf. cong. att. 3ª sg.', '(il buco storico!)')
T('amavisse', 'amo', 'inf. pf. att.')
T('amare', 'amo', 'inf. pres. att.')
T('amari', 'amo', 'inf. pres. pass.')
T('amatur', 'amo', 'pres. ind. pass. 3ª sg.')
T('amabatur', 'amo', 'impf. ind. pass. 3ª sg.')
T('amabitur', 'amo', 'fut. ind. pass. 3ª sg.')
T('ametur', 'amo', 'pres. cong. pass. 3ª sg.')
T('amans', 'amo', 'ptc. pres. nom. sg.')
T('amantis', 'amo', 'ptc. pres. gen. sg.')
T('amatus', 'amo', 'ptc. pf. nom. m. sg.')
T('amandus', 'amo', 'gerundivo nom. m. sg.')
print('— 2ª/3ª/mista/4ª coniugazione —')
T('monet', 'moneo', 'pres. ind. att. 3ª sg.')
T('monuit', 'moneo', 'pf. ind. att. 3ª sg.', '(uī → monu-)')
T('monitus', 'moneo', 'ptc. pf. nom. m. sg.')
T('ducit', 'duco', 'pres. ind. att. 3ª sg.')
T('ducet', 'duco', 'fut. ind. att. 3ª sg.', '(fut. di 3ª in -et)')
T('ducat', 'duco', 'pres. cong. att. 3ª sg.')
T('duxit', 'duco', 'pf. ind. att. 3ª sg.', '(ūxī → dūx-)')
T('ductus', 'duco', 'ptc. pf. nom. m. sg.', '(uctus → duct-)')
T('duci', 'duco', 'inf. pres. pass.', '(inf. pass. di 3ª in -ī)')
T('capit', 'capio', 'pres. ind. att. 3ª sg.')
T('capiunt', 'capio', 'pres. ind. att. 3ª pl.')
T('capiebat', 'capio', 'impf. ind. att. 3ª sg.')
T('capiet', 'capio', 'fut. ind. att. 3ª sg.')
T('cepit', 'capio', 'pf. ind. att. 3ª sg.', '(apofonia cēpī)')
T('captus', 'capio', 'ptc. pf. nom. m. sg.')
T('audit', 'audio', 'pres. ind. att. 3ª sg.')
T('audiebat', 'audio', 'impf. ind. att. 3ª sg.')
T('audivit', 'audio', 'pf. ind. att. 3ª sg.')
T('vidit', 'video', 'pf. ind. att. 3ª sg.')
T('visus', 'video', 'ptc. pf. nom. m. sg.')
print('— deponenti —')
T('conatur', 'conor', 'pres. ind. 3ª sg.')
T('conabatur', 'conor', 'impf. ind. 3ª sg.')
T('conari', 'conor', 'inf. pres. dep.')
T('conatus', 'conor', 'ptc. pf. nom. m. sg.')
print()
print('TUTTI I PARADIGMI OK' if fail == 0 else f'{fail} FALLITI')
sys.exit(1 if fail else 0)
