# -*- coding: utf-8 -*-
"""Titoli italiani degli autori minori — GENERATO, non modificare a mano.

Lo genera _gen_titoli_resto.py; le scelte fatte a mano stanno in
corpus_titles.py e VINCONO su queste (vedi la coda di quel file).

Vale la stessa regola del resto del catalogo: se la traduzione italiana del
titolo esiste nell'uso, va in testa e l'originale scende in seconda fascia.
`None` non vuol dire «non tradotto»: vuol dire che in italiano l'opera si cita
con il suo titolo originale, e allora la scheda ne stampa una fascia sola.

362 opere · 312 con titolo italiano · 50 lasciate all'originale.
"""

# id opera → titolo italiano d'uso, oppure None se l'uso È l'originale
TITOLI_RESTO = {
    "phi0426.phi001":      "La guerra africana",                          # In linea con «La guerra gallica» e «La guerra civile» del corpus cesari…
    "phi0428.phi001":      "La guerra alessandrina",                      # Titolo italiano corrente delle traduzioni del corpus cesariano; in lati…
    "phi0430.phi001":      "La guerra ispanica",                          # Resa italiana corrente; circola anche «La guerra di Spagna» e il latino…
    "phi0478.phi003":      None,                                          # L'operetta in italiano si cita sempre col titolo latino: le rese modern…
    "phi0692.phi001":      None,                                          # In italiano si cita sempre «le Dirae»: la glossa «Le imprecazioni» comp…
    "phi0692.phi002":      None,                                          # Il titolo è il nome della donna cantata: resta «Lydia» anche nelle ediz…
    "phi0692.phi003":      None,                                          # Manuali ed edizioni italiane dicono «il Culex»; «La zanzara» circola so…
    "phi0692.phi005":      None,                                          # Anche le traduzioni italiane conservano il titolo latino (Paravia: «Le …
    "phi0692.phi006":      "Elegie a Mecenate",                           # Titolo descrittivo, non nome proprio: la forma italiana «Elegie a Mecen…
    "phi0692.phi007":      None,                                          # «Ciris» è il nome dell'uccello in cui è mutata Scilla: in italiano non …
    "phi0692.phi008":      None,                                          # «Priapea» è già la forma con cui l'italiano cita il gruppo di carmi pri…
    "phi0692.phi009":      None,                                          # Titolo greco tradizionale ormai intraducibile: in italiano si dice «il …
    "phi0692.phi011":      None,                                          # «Il Moretum» è insieme il nome del piatto e il titolo d'uso anche nelle…
    "phi0692.phi012":      None,                                          # Si cita col titolo latino: nessuna resa italiana («L'educazione dell'uo…
    "phi0692.phi013":      None,                                          # Titolo latino formulare (il «sì» e il «no» della disputa): l'italiano n…
    "phi0836.phi002":      "Della medicina",                              # Titolo della versione italiana di riferimento («Della medicina, libri o…
    "phi0845.phi002":      "L'arte dell'agricoltura",                     # Titolo dell'edizione Einaudi (trad. Calzecchi Onesti), ormai corrente i…
    "phi0860.phi001":      "Storie di Alessandro Magno",                  # Titolo italiano corrente nelle edizioni e nei manuali.
    "phi0972.phi001f":     None,                                          # Frammenti: in italiano si citano con l'etichetta latina delle edizioni,…
    "phi1014.phi004":      None,                                          # Frammenti: si citano con l'etichetta latina delle edizioni.
    "phi1038.phi001":      "Detti e fatti memorabili",                    # Titolo italiano corrente (UTET), che inverte rispetto al latino l'ordin…
    "phi1242.phi001":      "Epitome di storia romana",                    # Titolo dell'edizione italiana (Rusconi, cura di Salomone Gaggero) e for…
    "phi2003.phi001":      "L'arte culinaria",                            # Titolo dell'edizione italiana più diffusa (Bompiani, cura di G. Carazza…
    "stoa0040.stoa011":    "Lettere",                                     # «Selections.» è una nota di catalogo Perseus (il testo è un'antologia),…
    "stoa0045.stoa001":    None,                                          # Il libretto si cita col nome della fanciulla, «Bissula»: non esiste res…
    "stoa0045.stoa002":    None,                                          # In italiano si citano «i Caesares» (così anche la bibliografia italiana…
    "stoa0045.stoa003":    "Centone nuziale",                             # «Centone nuziale» è la resa corrente in italiano (Treccani parla dell'«…
    "stoa0045.stoa004":    "Commemorazione dei professori di Bordeaux",   # Il catalogo in versi dei maestri bordolesi si designa in italiano con q…
    "stoa0045.stoa005":    "Cupido messo in croce",                       # È il titolo dell'edizione italiana corrente (Franzoi, Loffredo 2002), n…
    "stoa0045.stoa006":    None,                                          # Il poemetto sul podere avito si cita col titolo latino De herediolo; «i…
    "stoa0045.stoa007":    None,                                          # Si cita «Eclogae / Eclogarum liber»: in italiano «Egloghe» evocherebbe …
    "stoa0045.stoa008":    None,                                          # Il grecismo latinizzato «Ephemeris» è entrato tale e quale nell'uso ita…
    "stoa0045.stoa009":    None,                                          # Si cita col titolo latino «Epicedion in patrem»; «epicedio per il padre…
    "stoa0045.stoa010":    "Epigrammi",                                   # Il liber epigrammaton si cita in italiano come «Epigrammi», al pari di …
    "stoa0045.stoa011":    "Epistole",                                    # Edizioni e critica italiana usano «Epistole» (Decimo Magno Ausonio, Epi…
    "stoa0045.stoa012":    "Epitaffi",                                    # Treccani elenca fra le opere gli «epitaffi» (degli eroi caduti a Troia)…
    "stoa0045.stoa013":    None,                                          # Si cita col titolo greco-latino «Genethliacon», come il Protrepticus: «…
    "stoa0045.stoa014":    None,                                          # Formula latina consolidata («Gratiarum actio ad Gratianum imperatorem»)…
    "stoa0045.stoa015":    None,                                          # La bibliografia italiana lo chiama «il Griphus»; «enigma del numero tre…
    "stoa0045.stoa016":    None,                                          # Si cita «Protrepticus ad nepotem»: il termine è tecnico e resta latino …
    "stoa0045.stoa017":    None,                                          # È la rubrica editoriale della conclusione dei perduti Fasti (perciò le …
    "stoa0045.stoa018":    None,                                          # Anche le edizioni italiane portano il titolo latino (Cazzuffi 2014); «i…
    "stoa0045.stoa019":    None,                                          # Il nome del fiume coincide in italiano: si cita «Mosella» (al più «La M…
    "stoa0045.stoa020":    None,                                          # Titolo tecnico latino (l'orazione in versi ropalici): nessuna resa ital…
    "stoa0045.stoa021":    "Ordine delle città celebri",                  # Resa dell'edizione italiana UTET (Pastorino), corrente accanto al latin…
    "stoa0045.stoa022":    None,                                          # «Parentalia» è il nome della festa romana dei defunti ed è passato inta…
    "stoa0045.stoa025":    None,                                          # Diminutivo d'autore che si cita in latino: «prefazioncelle» non esiste …
    "stoa0045.stoa026":    None,                                          # Le preghiere liminari si citano col titolo latino «Precationes».
    "stoa0045.stoa027":    None,                                          # Si cita «Versus paschales (prosodici)»; «Versi pasquali» non è titolo a…
    "stoa0045.stoa028":    None,                                          # Grecismo tecnico entrato intatto nell'uso italiano: si cita «il Technop…
    "stoa0054.stoa006":    "Storia ecclesiastica degli Angli",            # «Storia ecclesiastica del popolo degli Inglesi» non è un titolo di ness…
    "stoa0058.stoa006":    None,                                          # Gli opuscoli teologici di Boezio in italiano si citano con i titoli lat…
    "stoa0089.stoa001":    None,                                          # Raccolta editoriale che in italiano si cita con la forma latina «Carmin…
    "stoa0089.stoa002":    "La guerra gildonica",                         # Resa corrente nella manualistica italiana e in Treccani («guerra gildon…
    "stoa0089.stoa003":    "La guerra gotica",                            # Resa corrente in italiano (anche «La guerra dei Goti»); l'opera si cita…
    "stoa0089.stoa004":    "Il consolato di Stilicone",                   # Resa italiana d'uso del panegirico consolare (anche «Panegirico per il …
    "stoa0089.stoa005":    "Il ratto di Proserpina",                      # Titolo tradizionale delle traduzioni italiane; le edizioni recenti pref…
    "stoa0089.stoa006":    "Epitalamio per le nozze di Onorio Augusto",   # Formula italiana d'uso per gli epitalami claudianei (si cita anche «Epi…
    "stoa0089.stoa007":    "Fescennini per le nozze di Onorio Augusto",   # Formula italiana d'uso («versi fescennini per le nozze di Onorio»).
    "stoa0089.stoa008":    "Contro Eutropio",                             # Resa italiana costante delle invettive claudianee (Treccani, manuali).
    "stoa0089.stoa009":    "Contro Rufino",                               # Resa italiana costante delle invettive claudianee (Treccani, manuali).
    "stoa0089.stoa010":    "Panegirico per il terzo consolato di Onorio Augusto", # I panegirici consolari si citano in italiano con la formula descrittiva…
    "stoa0089.stoa011":    "Panegirico per il quarto consolato di Onorio Augusto", # I panegirici consolari si citano in italiano con la formula descrittiva…
    "stoa0089.stoa012":    "Panegirico per il sesto consolato di Onorio Augusto", # I panegirici consolari si citano in italiano con la formula descrittiva…
    "stoa0089.stoa013":    "Panegirico per il consolato di Manlio Teodoro", # «Panegirico per il console Manlio Teodoro» e' un calco del dativo latin…
    "stoa0089.stoa014":    "Panegirico per i consoli Probino e Olibrio",  # Formula italiana d'uso, con i nomi dei consoli italianizzati.
    "stoa0162.stoa004":    "Lettere",                                     # «Selections.» è una nota di catalogo bibliotecario, non parte del titol…
    "stoa0203.stoa001":    "Ottavio",                                     # Titolo italiano consolidato del dialogo (edizione Pellegrino-Siniscalco…
    "stoa0238.stoa001":    "Le corone dei martiri",                       # Titolo delle edizioni italiane correnti (Città Nuova, «Le corone dei ma…
    "stoa0238.stoa002":    None,                                          # Nei manuali italiani è sempre «Psychomachia»; «La lotta per l'anima» co…
    "stoa0238.stoa003":    None,                                          # Etichetta latina conservata anche dalle edizioni italiane («aggiunti la…
    "stoa0238.stoa004":    "Inni quotidiani",                             # «Inni quotidiani» è il titolo delle traduzioni italiane; la forma corre…
    "stoa0238.stoa005":    None,                                          # Si cita col titolo latino «Apotheosis»; «Apoteosi» resta una glossa dei…
    "stoa0238.stoa006":    None,                                          # Titolo grecizzante d'uso corrente in italiano; «L'origine del male» è s…
    "stoa0238.stoa007":    "Contro Simmaco",                              # Formula polemica consolidata in italiano, come «Contro Apione» o «Contr…
    "stoa0238.stoa008":    None,                                          # Titolo greco enigmatico («doppio nutrimento»): in italiano si cita semp…
    "stoa0238.stoa009":    None,                                          # Come la Praefatio, etichetta latina mantenuta nelle edizioni italiane d…
    "stoa0261.stoa0001":   "Carmi",                                       # La raccolta poetica di Sidonio si cita correntemente in italiano come «…
    "stoa0261.stoa0002":   "Lettere, libri VIII-IX",                      # Il titolo in catalogo è ibrido, con l'inglese «Books»: va uniformato al…
    "stoa0275.stoa001":    "Ai martiri",                                  # Resa costante delle traduzioni italiane (Città Nuova, Opere apologetich…
    "stoa0275.stoa002":    "Ai pagani",                                   # Titolo dell'edizione italiana di riferimento (Città Nuova) e della voce…
    "stoa0275.stoa003":    "A Scapula",                                   # L'indirizzo al proconsole d'Africa si volge normalmente in italiano (Ci…
    "stoa0275.stoa004":    "Contro Ermogene",                             # Titolo italiano corrente, con il nome dell'avversario italianizzato (ed…
    "stoa0275.stoa005":    "Contro i Giudei",                             # Resa d'uso nella manualistica italiana; Città Nuova preferisce «Polemic…
    "stoa0275.stoa006":    "Contro Marcione",                             # Titolo dell'edizione italiana integrale (Città Nuova, Opere dottrinali:…
    "stoa0275.stoa007":    "Contro Prassea",                              # Titolo italiano corrente (Città Nuova, Opere dottrinali/4).
    "stoa0275.stoa008":    "Contro i Valentiniani",                       # Resa italiana consolidata della serie polemica «Adversus».
    "stoa0275.stoa009":    None,                                          # L'uso italiano è il titolo latino, come indicato dal docente: nei manua…
    "stoa0275.stoa010":    "L'anima",                                     # Titolo delle traduzioni italiane correnti (Città Nuova, Opere dottrinal…
    "stoa0275.stoa011":    "Il battesimo",                                # Titolo italiano corrente (Città Nuova, Opere catechetiche).
    "stoa0275.stoa012":    "La carne di Cristo",                          # Titolo italiano corrente (Città Nuova, Opere dottrinali/3).
    "stoa0275.stoa013":    "La corona",                                   # Titolo italiano corrente (Città Nuova, Opere montaniste/1); si trova an…
    "stoa0275.stoa014":    "L'eleganza delle donne",                      # Titolo dell'edizione italiana più diffusa (Isetta, EDB Biblioteca patri…
    "stoa0275.stoa015":    "Esortazione alla castità",                    # Titolo italiano corrente (Città Nuova, Opere montaniste/1).
    "stoa0275.stoa016":    "La fuga in tempo di persecuzione",            # Titolo dell'edizione italiana di riferimento (Città Nuova, Opere montan…
    "stoa0275.stoa017":    "L'idolatria",                                 # Titolo italiano corrente (Città Nuova, Opere montaniste/1).
    "stoa0275.stoa018":    "Il digiuno contro gli psichici",              # Titolo dell'edizione italiana di riferimento (Città Nuova, Opere montan…
    "stoa0275.stoa019":    "Le uniche nozze",                             # Titolo italiano consolidato (Uglione, Corona Patrum; Città Nuova); «La …
    "stoa0275.stoa020":    "La preghiera",                                # Titolo italiano corrente (Città Nuova, Opere catechetiche).
    "stoa0275.stoa021":    "La penitenza",                                # Titolo italiano corrente (Città Nuova, Opere catechetiche).
    "stoa0275.stoa022":    None,                                          # In italiano l'opera si cita sempre «De pallio» (così le edizioni Marra,…
    "stoa0275.stoa023":    "La pazienza",                                 # Titolo italiano corrente (Città Nuova, Opere catechetiche).
    "stoa0275.stoa024":    "Le prescrizioni contro gli eretici",          # Forma italiana consolidata (anche voce enciclopedica omonima); variante…
    "stoa0275.stoa025":    "La pudicizia",                                # Titolo italiano corrente (Città Nuova, Opere montaniste/2).
    "stoa0275.stoa026":    "La resurrezione della carne",                 # Titolo italiano corrente (Città Nuova, Opere dottrinali/4); dove si seg…
    "stoa0275.stoa027":    "Gli spettacoli",                              # Titolo italiano corrente (Città Nuova, Opere catechetiche).
    "stoa0275.stoa028":    "La testimonianza dell'anima",                 # Titolo italiano corrente (Città Nuova, Opere apologetiche vol. 1).
    "stoa0275.stoa029":    "Il velo delle vergini",                       # Titolo dell'edizione italiana di riferimento (Città Nuova, Opere montan…
    "stoa0275.stoa030":    None,                                          # Titolo grecizzante coniato dall'autore (σκορπίακον, «antidoto contro lo…
    "stoa0276.stoa002":    "Alla moglie",                                 # Titolo della traduzione italiana (Città Nuova; anche «Alla sposa» nell'…
    "tlg0004.tlg001":      "Vite e dottrine dei più celebri filosofi",    # Titolo dell'edizione italiana di riferimento (Reale, Bompiani), che ric…
    "tlg0008.tlg001":      "I Deipnosofisti",                             # L'uso italiano è la forma italianizzata «I Deipnosofisti» (ed. Salerno:…
    "tlg0017.tlg001":      "Per l'eredità di Cleonimo",                   # Formula consolidata delle orazioni ereditarie di Iseo («Per l'eredità d…
    "tlg0017.tlg002":      "Per l'eredità di Menecle",                    # Stessa formula d'uso italiano per i λόγοι κληρικοί di Iseo.
    "tlg0017.tlg003":      "Per l'eredità di Pirro",                      # Formula consolidata; l'originale greco in catalogo è corretto.
    "tlg0017.tlg004":      "Per l'eredità di Nicostrato",                 # La giustificazione fraintende il termine tecnico dell'intestazione grec…
    "tlg0017.tlg005":      "Per l'eredità di Diceogene",                  # Δικαιογένης si italianizza in «Diceogene»; formula d'uso invariata.
    "tlg0017.tlg006":      "Per l'eredità di Filottemone",                # Φιλοκτήμων dà in italiano «Filottemone» (assimilazione -κτ- > -tt-, com…
    "tlg0017.tlg007":      "Per l'eredità di Apollodoro",                 # Il catalogo ha «Απολλοδώρου» senza spirito: va restituito Ἀπολλοδώρου.
    "tlg0017.tlg008":      "Per l'eredità di Cirone",                     # Κίρων dà «Cirone»; formula d'uso invariata.
    "tlg0017.tlg009":      "Per l'eredità di Astifilo",                   # Formula consolidata; l'originale greco in catalogo è corretto.
    "tlg0017.tlg010":      "Per l'eredità di Aristarco",                  # L'uso italiano cita il discorso dal solo κλῆρος conteso, lasciando cade…
    "tlg0017.tlg011":      "Per l'eredità di Agnia",                      # Ἁγνίας si italianizza in «Agnia», lo stesso κλῆρος del «Contro Macartat…
    "tlg0017.tlg012":      "In difesa di Eufileto",                       # Il catalogo ha «Υπὲρ» senza spirito aspro; in italiano l'orazione (tràd…
    "tlg0023.tlg001":      "Alieutiche",                                  # Forma italianizzata d'uso nei manuali («le Alieutiche»); Treccani gloss…
    "tlg0024.tlg001":      "Cinegetiche",                                 # Come per le Alieutiche, forma italianizzata d'uso corrente; Treccani gl…
    "tlg0027.tlg001":      "Sui misteri",                                 # Titolo italiano consolidato dell'orazione.
    "tlg0027.tlg002":      "Sul suo ritorno",                             # Titolo italiano corrente nelle edizioni; circola anche «Sul proprio rit…
    "tlg0027.tlg003":      "Sulla pace con gli Spartani",                 # Titolo italiano consolidato (edizioni e commenti recenti); variante «Su…
    "tlg0027.tlg004":      "Contro Alcibiade",                            # Formula consolidata delle orazioni attiche (l'orazione è peraltro riten…
    "tlg0028.tlg001":      "Per avvelenamento contro la matrigna",        # La forma proposta ricalca l'ordine del greco (κατὰ τῆς μητρυιᾶς φαρμακε…
    "tlg0028.tlg002":      "Prima tetralogia",                            # Le Τετραλογίαι si citano in italiano come Prima, Seconda e Terza tetral…
    "tlg0028.tlg003":      "Seconda tetralogia",                          # Numerazione italiana corrente della serie delle tetralogie.
    "tlg0028.tlg004":      "Terza tetralogia",                            # Numerazione italiana corrente della serie delle tetralogie.
    "tlg0028.tlg005":      "Sull'omicidio di Erode",                      # Titolo italiano d'uso del De caede Herodis (anche «Per l'uccisione di E…
    "tlg0028.tlg006":      "Sul coreuta",                                 # Formula consolidata dell'oratoria attica in italiano, con il tecnicismo…
    "tlg0029.tlg004":      "Contro Demostene",                            # Formula consolidata per le orazioni attiche in κατά + genitivo.
    "tlg0029.tlg005":      "Contro Aristogitone",                         # Formula consolidata per le orazioni attiche in κατά + genitivo.
    "tlg0029.tlg006":      "Contro Filocle",                              # Formula consolidata per le orazioni attiche in κατά + genitivo.
    "tlg0030.tlg001":      "Per Licofrone",                               # Formula consolidata delle orazioni attiche in italiano (il greco suona …
    "tlg0030.tlg002":      "Contro Filippide",                            # Titolo italiano consolidato dell'orazione.
    "tlg0030.tlg003":      "Contro Atenogene",                            # Titolo italiano consolidato, fra i più citati di Iperide.
    "tlg0030.tlg004":      "Per Eussenippo",                              # In italiano si cita «Per Eussenippo»; nel greco in catalogo lo spirito …
    "tlg0030.tlg005":      "Contro Demostene",                            # Formula d'uso; per esteso «Contro Demostene, per il denaro di Arpalo».
    "tlg0030.tlg006":      "Epitafio",                                    # L'orazione funebre di Iperide si cita in italiano come «Epitafio».
    "tlg0031.tlg001":      "Vangelo secondo Matteo",                      # Titolo italiano corrente (CEI); in catalogo il nome era al nominativo e…
    "tlg0031.tlg002":      "Vangelo secondo Marco",                       # Titolo italiano corrente; ripristinata la formula «Κατὰ» + accusativo p…
    "tlg0031.tlg003":      "Vangelo secondo Luca",                        # Titolo italiano corrente; l'accusativo in catalogo tradiva la formula t…
    "tlg0031.tlg004":      "Vangelo secondo Giovanni",                    # Titolo italiano corrente; reintegrata la formula «Κατὰ» davanti all'acc…
    "tlg0031.tlg005":      "Atti degli Apostoli",                         # In catalogo c'era addirittura l'inglese «Acts» su un'opera greca: l'ori…
    "tlg0031.tlg006":      "Lettera ai Romani",                           # Titolo italiano corrente; l'originale mancava di «Πρὸς» e dello spirito…
    "tlg0031.tlg007":      "Prima lettera ai Corinzi",                    # Titolo italiano corrente; reintegrato «Πρὸς» e normalizzato il numerale…
    "tlg0031.tlg008":      "Seconda lettera ai Corinzi",                  # Titolo italiano corrente; reintegrato «Πρὸς» e normalizzato il numerale…
    "tlg0031.tlg009":      "Lettera ai Galati",                           # Titolo italiano corrente; reintegrata la preposizione «Πρὸς» del titolo…
    "tlg0031.tlg010":      "Lettera agli Efesini",                        # Titolo italiano corrente; reintegrata la preposizione «Πρὸς».
    "tlg0031.tlg011":      "Lettera ai Filippesi",                        # Titolo italiano corrente; l'originale in catalogo era guasto (Φιλιππηνί…
    "tlg0031.tlg012":      "Lettera ai Colossesi",                        # Titolo italiano corrente; corretta la grafia (Κολασσαείς è variante del…
    "tlg0031.tlg013":      "Prima lettera ai Tessalonicesi",              # Titolo italiano corrente; reintegrato «Πρὸς», corretto l'accusativo plu…
    "tlg0031.tlg014":      "Seconda lettera ai Tessalonicesi",            # Titolo italiano corrente; reintegrato «Πρὸς», corretto l'accusativo plu…
    "tlg0031.tlg015":      "Prima lettera a Timoteo",                     # Titolo italiano corrente; reintegrato «Πρὸς» e numerale col segno greco…
    "tlg0031.tlg016":      "Seconda lettera a Timoteo",                   # Titolo italiano corrente; tolto il carattere «>» spurio, reintegrato «Π…
    "tlg0031.tlg017":      "Lettera a Tito",                              # Titolo italiano corrente; reintegrata la preposizione «Πρὸς».
    "tlg0031.tlg018":      "Lettera a Filemone",                          # Titolo italiano corrente; reintegrata la preposizione «Πρὸς».
    "tlg0031.tlg019":      "Lettera agli Ebrei",                          # Titolo italiano corrente; reintegrata la preposizione «Πρὸς».
    "tlg0031.tlg020":      "Lettera di Giacomo",                          # Titolo italiano corrente; il greco «Ἰακώβου» è già l'intestazione tràdi…
    "tlg0031.tlg021":      "Prima lettera di Pietro",                     # Titolo italiano corrente; il greco va bene, si normalizza solo il numer…
    "tlg0031.tlg022":      "Seconda lettera di Pietro",                   # Titolo italiano corrente; in catalogo il numerale era una B latina, va …
    "tlg0031.tlg023":      "Prima lettera di Giovanni",                   # Titolo italiano corrente; normalizzato il numerale col segno greco Α΄.
    "tlg0031.tlg024":      "Seconda lettera di Giovanni",                 # Titolo italiano corrente; normalizzato il numerale col segno greco Β΄.
    "tlg0031.tlg025":      "Terza lettera di Giovanni",                   # Titolo italiano corrente; normalizzato il numerale col segno greco Γ΄.
    "tlg0031.tlg026":      "Lettera di Giuda",                            # Titolo italiano corrente; il genitivo in catalogo era guasto (Ἰούδου): …
    "tlg0031.tlg027":      "Apocalisse",                                  # In italiano si cita «Apocalisse» senza altro; l'originale tràdito porta…
    "tlg0034.tlg001":      "Contro Leocrate",                             # Formula consolidata delle orazioni attiche: κατά + genitivo si rende «C…
    "tlg0035.tlg001":      "Amore fuggitivo",                             # Titolo con cui l'idillio circola in italiano (variante «Eros fuggitivo»…
    "tlg0035.tlg002":      "Europa",                                      # L'epillio si cita in italiano col nome dell'eroina, «Europa».
    "tlg0035.tlg003":      "Epitafio di Bione",                           # Formula italiana consolidata per il compianto (di paternità discussa) s…
    "tlg0035.tlg004":      "Megara",                                      # Si cita in italiano col nome della moglie di Eracle, «Megara».
    "tlg0035.tlg005":      None,                                          # «Fragmenta» è etichetta editoriale moderna, non un titolo d'autore: non…
    "tlg0036.tlg001":      "Epitafio di Adone",                           # Il titolo in catalogo è privo di spiriti e accenti: restituito il polit…
    "tlg0036.tlg002":      "Epitalamio di Achille e Deidamia",            # In italiano il carme si cita sempre come Epitalamio di Achille e Deidam…
    "tlg0036.tlg003":      None,                                          # Raccolta di frammenti: in italiano si cita con l'etichetta latina delle…
    "tlg0057.tlg010":      "Sulle facoltà naturali",                      # In catalogo «Περί» porta l'acuto invece del grave davanti alla parola s…
    "tlg0058.tlg001":      "La difesa di una città assediata",            # Titolo dell'edizione italiana di riferimento (Bettalli, ETS 1990); nei …
    "tlg0074.tlg001":      "Anabasi di Alessandro",                       # Titolo italiano delle edizioni correnti (Mondadori, BUR); «Anabasis» è …
    "tlg0074.tlg002":      "Indiké",                                      # L'italiano cita «Indiké» (Sisti-Zambrini; «L'Indiké di Arriano»): trasl…
    "tlg0074.tlg003":      "Cinegetico",                                  # Forma italiana d'uso, sul modello del Cinegetico senofonteo; «La caccia…
    "tlg0074.tlg004":      "Periplo del Ponto Eusino",                    # Titolo italiano consolidato (ed. Marenghi e bibliografia successiva).
    "tlg0074.tlg005":      "L'arte tattica",                              # Titolo dell'edizione italiana con testo greco a fronte («L'arte tattica…
    "tlg0074.tlg006":      "Schieramento contro gli Alani",               # Titolo italiano corrente, usato anche come titolo di volume.
    "tlg0081.tlg001":      "Antichità romane",                            # Titolo italiano corrente e consolidato per la Ῥωμαϊκὴ Ἀρχαιολογία; l'or…
    "tlg0081.tlg002":      "Sugli antichi oratori",                       # Resa italiana corrente del De antiquis oratoribus, usata dai manuali (a…
    "tlg0081.tlg003":      "Su Lisia",                                    # La riga in catalogo riproduce un pezzo dell'incipit («Λυσίας... Συρακού…
    "tlg0081.tlg004":      "Su Isocrate",                                 # Come sopra: in catalogo c'è l'incipit (per giunta senza accento su Ἰσοκ…
    "tlg0081.tlg005":      "Su Iseo",                                     # Anche qui il catalogo dà l'incipit e non il titolo, che nelle edizioni …
    "tlg0081.tlg006":      "Sullo stile di Demostene",                    # Titolo italiano d'uso per il De Demosthene; l'originale in catalogo è p…
    "tlg0081.tlg007":      "Sugli antichi oratori, resti del libro II",   # Titolo latino editoriale su opera greca: sono i resti del secondo libro…
    "tlg0081.tlg008":      "Prima lettera ad Ammeo",                      # È l'Epistula ad Ammaeum I, che in italiano si cita «Prima lettera ad Am…
    "tlg0081.tlg009":      "Su Dinarco",                                  # Resa italiana corrente del De Dinarcho, uniforme agli altri opuscoli («…
    "tlg0081.tlg010":      "Su Tucidide",                                 # Il catalogo ha la grafia itacistica Θουκιδίδου: il nome si scrive Θουκυ…
    "tlg0081.tlg011":      "Seconda lettera ad Ammeo",                    # È l'Epistula ad Ammaeum II, citata in italiano come «Seconda lettera ad…
    "tlg0081.tlg012":      "Sulla composizione delle parole",             # Forma italiana più diffusa nei manuali per il De compositione verborum …
    "tlg0081.tlg015":      "Lettera a Pompeo Gemino",                     # Il destinatario è Pompeo Gemino e così l'opera si cita in italiano; l'o…
    "tlg0093.tlg009":      "I caratteri",                                 # Titolo italiano universale dell'operetta teofrastea.
    "tlg0094.tlg002":      "La musica",                                   # Resa italiana corrente del De musica pseudoplutarcheo nelle traduzioni …
    "tlg0094.tlg003":      None,                                          # «Opinioni dei filosofi sulla natura» non è verificabile in nessuna sede…
    "tlg0284.tlg001":      "Inno a Zeus",                                 # Primo degli inni in prosa (or. 43 K): in italiano la serie si cita come…
    "tlg0284.tlg002":      "Inno ad Atena",                               # Or. 37 K, l'inno in prosa ad Atena: così è designato anche nella recens…
    "tlg0284.tlg003":      "Discorso istmico a Poseidone",                # Or. 46 K, panegirico religioso pronunciato all'Istmo; «Istmico a Poseid…
    "tlg0284.tlg004":      "Inno a Dioniso",                              # Or. 41 K, inno in prosa: stessa serie e stessa formula degli altri inni…
    "tlg0284.tlg005":      "Inno a Eracle",                               # TITOLO GUASTO: il catalogo ripete «Ἰσθμικὸς εἰς Ποσειδῶνα» di tlg003 pe…
    "tlg0284.tlg006":      "Lalia per Asclepio",                          # Or. 42 K: λαλιά è termine tecnico di genere (il discorso «di conversazi…
    "tlg0284.tlg007":      "Gli Asclepiadi",                              # Or. 38 K, per i figli di Asclepio: il nome è già italianissimo (Asclepi…
    "tlg0284.tlg008":      "Inno a Serapide",                             # Or. 45 K; forma già attestata in italiano («l'inno a Serapide di Elio A…
    "tlg0284.tlg009":      "Al re",                                       # Or. 35 K, encomio di un imperatore (βασιλεύς = l'imperatore romano); l'…
    "tlg0284.tlg010":      "Genetliaco per Apella",                       # Or. 30 K: «genetliaco» è il nome italiano corrente del γενεθλιακός, e l…
    "tlg0284.tlg011":      "Epicedio per Eteoneo",                        # Titolo italiano attestato letteralmente: E. Berardi, «Elio Aristide, Ep…
    "tlg0284.tlg012":      "Epitafio per Alessandro",                     # Titolo italiano attestato letteralmente nello stesso volume Berardi 200…
    "tlg0284.tlg013":      "Panatenaico",                                 # Titolo italiano consolidato e da manuale (Treccani; tesi e studi italia…
    "tlg0284.tlg014":      "Encomio di Roma",                             # Forma di Treccani, aderente al greco Ῥώμης ἐγκώμιον; in Italia circolan…
    "tlg0284.tlg015":      "Primo discorso smirneo",                      # Nessuna fonte italiana usa «Discorso politico smirneo», che in italiano…
    "tlg0284.tlg016":      "Discorso panegirico a Cizico per il tempio",  # Or. 27 K: resa piana e letterale del πανηγυρικός per l'inaugurazione de…
    "tlg0284.tlg017":      "Sul mare Egeo",                               # Or. 44 K; Treccani lo richiama come l'orazione «per l'Egeo». Preferisco…
    "tlg0284.tlg018":      "Sul pozzo di Asclepio",                       # Or. 39 K, sul φρέαρ sacro dell'Asclepieo di Pergamo: resa letterale, l'…
    "tlg0284.tlg019":      "Discorso per Eleusi",                         # «Eleusinio» non è la forma italiana: l'aggettivo da Eleusi è «eleusino»…
    "tlg0284.tlg020":      "Monodia per Smirne",                          # Or. 18 K, il lamento per il terremoto del 177: forma gemella della «Pal…
    "tlg0284.tlg021":      "Palinodia per Smirne",                        # Titolo italiano attestato («la Palinodia per Smirne, Or. XX Keil»); il …
    "tlg0284.tlg022":      "Secondo discorso smirneo",                    # Errore di destinatario, non solo di uso: Σμυρναϊκός vale «smirneo» (di/…
    "tlg0284.tlg023":      "Discorso sacro I",                            # Gli Ἱεροὶ λόγοι sono in italiano i «Discorsi sacri» (traduzione Nicosia…
    "tlg0284.tlg024":      "Discorso sacro II",                           # Secondo libro dei Discorsi sacri: numerazione romana come da uso italiano.
    "tlg0284.tlg025":      "Discorso sacro III",                          # Terzo libro dei Discorsi sacri.
    "tlg0284.tlg026":      "Discorso sacro IV",                           # Quarto libro dei Discorsi sacri.
    "tlg0284.tlg027":      "Discorso sacro V",                            # Quinto libro dei Discorsi sacri.
    "tlg0284.tlg028":      "Discorso sacro VI",                           # Sesto libro dei Discorsi sacri, frammentario nella tradizione ma numera…
    "tlg0284.tlg029":      "Sull'invio di rinforzi in Sicilia",           # Primo dei due «Discorsi siciliani» (orr. 5-6 K), che in italiano si des…
    "tlg0284.tlg030":      "Contro l'invio di rinforzi in Sicilia",       # «Sulla tesi contraria» è la resa meccanica di Εἰς τὸ ἐναντίον e su una …
    "tlg0284.tlg031":      "Sulla pace con gli Spartani",                 # Declamazione storica: resa letterale del titolo greco, con l'etnico e n…
    "tlg0284.tlg032":      "Sulla pace con gli Ateniesi",                 # Discorso gemello del precedente, pronunciato però dalla parte spartana;…
    "tlg0284.tlg033":      "Leuttrico I (in favore degli Spartani)",      # Treccani e la bibliografia italiana chiamano il ciclo «i Leuttrici» / «…
    "tlg0284.tlg034":      "Leuttrico II (in favore dei Tebani)",         # Stesso ciclo; correzione del numerale in Β΄ con keraia.
    "tlg0284.tlg035":      "Leuttrico III (in favore degli Spartani)",    # Stesso ciclo; correzione del numerale in Γ΄ con keraia.
    "tlg0284.tlg036":      "Leuttrico IV (in favore dei Tebani)",         # Stesso ciclo; correzione del numerale in Δ΄ con keraia.
    "tlg0284.tlg037":      "Leuttrico V (per la neutralità)",             # Chiude il ciclo con la tesi di non soccorrere né gli uni né gli altri, …
    "tlg0284.tlg038":      "Discorso sull'alleanza I",                    # Il συμμαχικός è il discorso «sull'alleanza» (come il Περὶ τῆς συμμαχίας…
    "tlg0284.tlg039":      "Discorso sull'alleanza II",                   # La parentesi è falsamente distintiva: ANCHE il primo Simmachico è rivol…
    "tlg0284.tlg040":      "Sull'abrogazione della commedia",             # Esiste già il titolo italiano corrente, e non è quello proposto: M. Lam…
    "tlg0284.tlg041":      "Lettera su Smirne",                           # Or. 19 K, la lettera a Marco Aurelio e Commodo dopo il terremoto: resa …
    "tlg0284.tlg042":      "Alle città per la concordia",                 # Forma di Treccani («le orazioni Alle città per la concordia»); ὁμόνοια …
    "tlg0284.tlg043":      "Rodiaco",                                     # «Rodiaco» è la forma di Treccani, grecismo ormai italiano come «Panaten…
    "tlg0284.tlg044":      "Ai Rodii per la concordia",                   # Forma di Treccani («Ai Rodî per la concordia»), con la grafia moderna «…
    "tlg0284.tlg045":      "In difesa della retorica",                    # Titolo italiano corrente e ripetutamente attestato negli studi («l'oraz…
    "tlg0284.tlg046":      "In difesa dei quattro",                       # Titolo italiano attestato (Treccani, «Difesa dei Quattro»; tesi e artic…
    "tlg0284.tlg047":      "Epistola a Capitone",                         # È il terzo dei «Discorsi platonici» e in italiano si cita così («l'Epis…
    "tlg0284.tlg048":      "Discorso egizio",                             # Or. 36 K, l'indagine sulle piene del Nilo; «Egizio» da solo sulla sched…
    "tlg0284.tlg049":      "Sull'affermazione in margine",                # Or. 28 K: è la resa con cui Miletti traduce παράφθεγμα (l'osservazione …
    "tlg0284.tlg050":      "Contro i profanatori",                        # Or. 34 K: ἐξορχεῖσθαι è «divulgare danzando», cioè profanare i misteri …
    "tlg0284.tlg051":      "A coloro che lo accusano di non declamare",   # Or. 33 K: μελετᾶν è tecnicamente «tenere declamazioni» (μελέται), non «…
    "tlg0284.tlg052":      "Ambasceria ad Achille",                       # Titolo italiano attestato alla lettera in E. Berardi («l'Ambasceria ad …
    "tlg0284.tlg053":      "Contro Demostene, sull'immunità",             # Declamazione (di paternità discussa) che ribatte alla demostenica Contr…
    "tlg0284.tlg054":      "Contro Leptine, in difesa dell'immunità",     # Discorso opposto al precedente: stesso titolo greco dell'orazione XX di…
    "tlg0284.tlg055":      "Panegirico per l'acqua di Pergamo",           # «Discorso panegirico» non è forma italiana: «panegirico» è già il sosta…
    "tlg0284.tlg056":      "Sul discorso politico",                       # Trattato retorico (Ars rhetorica I, attribuzione discussa): πολιτικὸς λ…
    "tlg0341.tlg002":      "Alessandra",                                  # Il poema di Licofrone si cita in italiano come «Alessandra», forma ital…
    "tlg0363.tlg007":      "Tetrabiblos",                                 # In italiano l'opera si cita «Tetrabiblos» (ed. Valla: «Le previsioni as…
    "tlg0385.tlg001":      "Storia romana",                               # «(Books 36-55)» indica i libri contenuti nel volume dell'edizione ed è …
    "tlg0526.tlg001":      "Antichità giudaiche",                         # Titolo con cui l'opera si cita in ogni manuale ed edizione italiana.
    "tlg0526.tlg002":      "Autobiografia",                               # In italiano si cita Autobiografia (o Vita); il greco Ἰωσήπου βίος resta…
    "tlg0526.tlg003":      "Contro Apione",                               # Il greco in catalogo è il titolo autentico; l'uso italiano (e la tradiz…
    "tlg0526.tlg004":      "La guerra giudaica",                          # Il catalogo conserva solo il genitivo pendente della formula: ripristin…
    "tlg0532.tlg001":      "Leucippe e Clitofonte",                       # In «Kλειτoφῶντα» il catalogo ha una K e una o latine al posto delle gre…
    "tlg0535.tlg001":      "Intorno ai dodici anni",                      # «Sui dodici anni» ricalca il titolo inglese con cui l'opera compare in …
    "tlg0545.tlg001":      "La natura degli animali",                     # Titolo delle edizioni italiane correnti (De natura animalium).
    "tlg0545.tlg002":      "Storie varie",                                # La giustificazione dice «resa corrente nelle edizioni italiane», ma l'u…
    "tlg0545.tlg003":      "Lettere rustiche",                            # Titolo dell'edizione italiana di riferimento (Drago 2023); il greco in …
    "tlg0548.tlg001":      "Biblioteca",                                  # Titolo italiano corrente del manuale mitografico.
    "tlg0548.tlg002":      "Epitome",                                     # L'accento grave vale solo davanti ad altra parola: in isolamento l'ossi…
    "tlg0551.tlg002":      "Storia dell'età regia",                       # «Storia dei re» non è attestato in nessuna fonte italiana: è la traduzi…
    "tlg0551.tlg003":      "Storia italica",                              # Ripristinato il nominativo come negli altri libri; in italiano è il lib…
    "tlg0551.tlg004":      "Le guerre sannitiche",                        # Formula italiana corrente (cfr. l'edizione «Appiano. Dalle guerre sanni…
    "tlg0551.tlg005":      "Storia celtica",                              # Il modulo «Guerra + aggettivo» in italiano è riservato ai libri conserv…
    "tlg0551.tlg006":      "Storia siciliana e isolana",                  # La perifrasi «Storia della Sicilia e delle isole» è una resa parola per…
    "tlg0551.tlg007":      "La guerra iberica",                           # Treccani cita in italiano «la Guerra iberica»; il greco in catalogo è g…
    "tlg0551.tlg008":      "La guerra annibalica",                        # Titolo italiano corrente registrato da Treccani per il libro annibaico.
    "tlg0551.tlg009":      "La guerra libica",                            # Treccani: «la Guerra libica», cioè lo scontro con Cartagine visto dall'…
    "tlg0551.tlg010":      "Storia numidica",                             # «ἐκ τῆς» è la rubrica degli estratti: il titolo è Νομαδική, in italiano…
    "tlg0551.tlg011":      "Le guerre macedoniche",                       # Ripristinato il nominativo; in italiano il libro si designa con le guer…
    "tlg0551.tlg012":      "La guerra illirica",                          # Treccani: «la Guerra illirica»; il titolo greco in catalogo è già quell…
    "tlg0551.tlg013":      "La guerra siriaca",                           # Treccani: «la Guerra siriaca» (la campagna contro Antioco III).
    "tlg0551.tlg014":      "La guerra mitridatica",                       # Treccani registra «la Guerra mitridatica»; l'edizione Mondadori la inti…
    "tlg0551.tlg017":      "Le guerre civili",                            # «Ἐμφυλίων Πρώτη» è l'intestazione del solo libro I, ma l'unità comprend…
    "tlg0554.tlg001":      "Le avventure di Cherea e Calliroe",           # «De Chaerea et Callirhoe» è titolo latino d'edizione su romanzo greco; …
    "tlg0555.tlg001":      "Protrettico ai Greci",                        # Titolo italiano corrente nelle edizioni e nei manuali di patristica.
    "tlg0555.tlg004":      "Stromati",                                    # Forma italianizzata d'uso («Gli Stromati»); il greco Στρώματα resta sotto.
    "tlg0555.tlg006":      "Quale ricco si salverà?",                     # Resa italiana consolidata del Quis dives salvetur, diffusa anche nella …
    "tlg0556.tlg001":      "Trattato di tattica",                         # Forma con cui il manuale circola in italiano (ed. Cascarino «Trattato d…
    "tlg0557.tlg004":      None,                                          # Silloge moderna di estratti da Stobeo: si cita con l'etichetta latina d…
    "tlg0557.tlg005":      None,                                          # Come la precedente: raccolta editoriale moderna, in italiano si cita co…
    "tlg0560.tlg001":      "Sul sublime",                                 # Titolo italiano corrente del Περὶ ὕψους; varianti in circolazione «Del …
    "tlg0612.tlg001":      "Orazioni",                                    # «Orationes» è titolo latino su corpus greco: l'originale è Λόγοι; in it…
    "tlg0613.tlg001":      "Sullo stile",                                 # Il Περὶ ἑρμηνείας è tramandato in italiano come «Sullo stile» (varianti…
    "tlg0627.tlg001":      "L'antica medicina",                           # Titolo italiano consolidato (Treccani, edizione Vegetti); il greco in c…
    "tlg0627.tlg003":      "Prognostico",                                 # «Prognostico» è il titolo con cui l'opera si cita in italiano; il greco…
    "tlg0627.tlg004":      "Il regime nelle malattie acute",              # Titolo italiano d'uso (anche «La dieta nelle malattie acute»); il greco…
    "tlg0627.tlg005":      "Il regime nelle malattie acute (appendice spuria)", # Stessa opera con la marca editoriale Νόθα, che in italiano si rende «ap…
    "tlg0627.tlg006":      "Epidemie",                                    # «Epidemie» è il titolo italiano corrente; il greco era mal accentato, i…
    "tlg0627.tlg007":      "Le ferite del capo",                          # Titolo italiano d'uso (De capitis vulneribus); il greco in catalogo è c…
    "tlg0627.tlg008":      "L'officina del medico",                       # Titolo italiano d'uso per il De officina medici (anche «l'ambulatorio d…
    "tlg0627.tlg009":      "Le fratture",                                 # Titolo italiano consolidato dei due trattati chirurgici gemelli; il gre…
    "tlg0627.tlg010":      "Le articolazioni",                            # Titolo italiano consolidato, gemello delle Fratture; il greco in catalo…
    "tlg0627.tlg011":      None,                                          # In italiano il trattatello si cita col titolo greco traslitterato («Moc…
    "tlg0627.tlg012":      "Aforismi",                                    # Titolo italiano corrente e notissimo; il greco in catalogo è corretto.
    "tlg0627.tlg013":      "Giuramento",                                  # «Iusiurandum» è il titolo latino convenzionale delle edizioni su un'ope…
    "tlg0627.tlg027":      "Il morbo sacro",                              # Titolo italiano consolidato (anche «La malattia sacra»); il greco ionic…
    "tlg0627.tlg028":      "Le ulcere",                                   # Titolo italiano d'uso (De ulceribus); il greco in catalogo è corretto.
    "tlg0627.tlg029":      "Le emorroidi",                                # Titolo italiano d'uso (De haemorrhoidibus); il greco in catalogo è corr…
    "tlg0627.tlg030":      "Le fistole",                                  # Titolo italiano d'uso (De fistulis); il greco in catalogo è corretto.
    "tlg0627.tlg046":      "Sul nutrimento",                              # Titolo italiano d'uso per il De alimento (anche «L'alimento»); il greco…
    "tlg0627.tlg051":      "Precetti",                                    # Titolo italiano d'uso (Praeceptiones); il greco in catalogo è corretto.
    "tlg0638.tlg001":      "Vita di Apollonio di Tiana",                  # Titolo italiano universale dell'opera; il greco in catalogo è già quell…
    "tlg0638.tlg003":      "Vite dei sofisti",                            # Titolo delle edizioni italiane (Sellerio) e degli studi.
    "tlg0638.tlg004":      "Eroico",                                      # «Eroico» è la forma italiana corrente per il dialogo di Filostrato.
    "tlg0638.tlg005":      "Nerone",                                      # Nome proprio con forma italiana d'uso immediata.
    "tlg0638.tlg006":      "Lettere. Dialexeis.",                         # «Lettere» regge (Wikipedia IT elenca fra le opere di Filostrato le «Let…
    "tlg0638.tlg007":      "Sulla ginnastica",                            # Resa italiana corrente (così Treccani); accanto circola il latino «Gymn…
    "tlg0641.tlg001":      "Racconti efesii",                             # Titolo italiano d'uso del romanzo (in alternativa «Efesiache»); il grec…
    "tlg0647.tlg001":      "La presa di Ilio",                            # Resa italiana consolidata di Ἅλωσις Ἰλίου, titolo dell'epillio di Trifi…
    "tlg0648.tlg001":      "Il generale",                                 # Titolo dell'edizione italiana di riferimento (Petrocelli, Dedalo: «Il g…
    "tlg0652.tlg001":      "Immagini",                                    # Le Εἰκόνες di Filostrato Minore si citano in italiano come «Immagini».
    "tlg0653.tlg001":      "Fenomeni",                                    # Titolo italiano corrente del poema astronomico di Arato (anche «I Fenom…
    "tlg0655.tlg001":      "Pene d'amore",                                # «Sofferenze d'amore» non è il titolo di nessuna edizione né di nessuna …
    "tlg0719.tlg001":      "Delle cause e dei segni delle malattie acute", # La giustificazione stessa ammette che «l'unica resa italiana in circola…
    "tlg0719.tlg002":      "Sulle cause e i segni delle malattie croniche", # Il greco in catalogo è già accentato bene; l'italiano fa coppia con tlg…
    "tlg0719.tlg003":      "La cura delle malattie acute",                # θεραπευτικόν è reso con «cura» nella sola versione italiana esistente; …
    "tlg0719.tlg004":      "La cura delle malattie croniche",             # «θεραπευτικών» è guasto: il titolo è il neutro θεραπευτικόν, come in tl…
    "tlg1216.tlg001":      "Lettera di Barnaba",                          # Resa italiana corrente, identica al nome con cui l'opera compare nelle …
    "tlg1389.tlg001":      "Lessico dei dieci oratori",                   # «Lexicon in decem oratores Atticos» è il titolo latino delle edizioni d…
    "tlg1600.tlg001":      "Immagini",                                    # Come per Filostrato Minore, le Εἰκόνες sono in italiano le «Immagini» (…
    "tlg1799.tlg001":      "Elementi",                                    # Titolo italiano universale del trattato euclideo («Gli Elementi»).
    "tlg2003.tlg001":      "Panegirico in onore dell'imperatore Costanzo", # Titolo italiano d'uso per l'ἐγκώμιον a Costanzo II (or. I).
    "tlg2003.tlg002":      "Elogio dell'imperatrice Eusebia",             # Resa italiana corrente dell'ἐγκώμιον per Eusebia (or. II/III a seconda …
    "tlg2003.tlg003":      "Sulle gesta dell'imperatore, ovvero sulla regalità", # Secondo panegirico a Costanzo, citato in italiano col titolo doppio che…
    "tlg2003.tlg005":      "Lettera al senato e al popolo di Atene",      # L'orazione-manifesto del 361 si cita in italiano così (o «Lettera agli …
    "tlg2003.tlg006":      "Lettera a Temistio",                          # Forma italiana consolidata per l'epistola-orazione al filosofo Temistio.
    "tlg2003.tlg008":      "Alla Madre degli dèi",                        # Titolo italiano d'uso per l'inno-orazione alla Magna Mater.
    "tlg2003.tlg009":      "Contro i cinici ignoranti",                   # Resa italiana corrente di Εἰς τοὺς ἀπαιδεύτους κύνας (ἀπαίδευτοι = priv…
    "tlg2003.tlg010":      "I Cesari",                                    # La satira Συμπόσιον ἢ Κρόνια si cita universalmente in italiano come «I…
    "tlg2003.tlg011":      "Inno a Helios Re",                            # Titolo italiano d'uso per il discorso dedicato a Salustio (anche «Disco…
    "tlg2003.tlg012":      None,                                          # In italiano l'opera si cita col titolo greco traslitterato, «Misopogon»…
    "tlg2003.tlg013":      "Lettere",                                     # Titolo latino su opera greca: l'epistolario di Giuliano è in greco (Ἐπι…
    "tlg2003.tlg017":      "Contro i Galilei",                            # Titolo latino convenzionale su opera greca: l'originale è Κατὰ Γαλιλαίω…
    "tlg2018.tlg002":      "Storia ecclesiastica",                        # Resa italiana consolidata di Ἐκκλησιαστικὴ ἱστορία, usata da tutte le e…
    "tlg2040.tlg002":      "Discorso ai giovani",                         # Titolo italiano consolidato dall'edizione Naldini (Oratio ad adolescent…
    "tlg2040.tlg004":      "Lettere",                                     # «Epistulae» è il titolo latino delle edizioni su un'opera greca: l'orig…
    "tlg2045.tlg001":      "Le Dionisiache",                              # Titolo italiano consolidato del poema di Nonno (ed. BUR «Le Dionisiache»).
    "tlg2046.tlg001":      "Posthomerica",                                # Nei manuali italiani il poema si cita col titolo convenzionale «Posthom…
    "tlg2934.tlg066":      "Barlaam e Ioasaf",                            # Accenti da correggere (ossitoni in grave davanti a parola seguente); in…
    "tlg3135.tlg001":      "Epitome delle storie",                        # Titolo italiano corrente dell'opera di Zonara (lat. Epitome historiarum…
    "tlg4029.tlg001":      "Le guerre",                                   # Titolo delle edizioni italiane («Le guerre persiana, vandalica, gotica»…
    "tlg4029.tlg002":      "Storia segreta",                              # «Ἀπόκρυφη Ἱστορία» è greco moderno: il titolo antico, attestato dalla S…
    "tlg4036.tlg023":      "Crestomazia",                                 # In catalogo c'è il titolo inglese «Chrestomathy»: l'originale è greco e…
    "tlg4081.tlg001":      "Il ratto di Elena",                           # Titolo italiano consolidato dell'epillio di Colluto.
    "tlg4091.tlg001":      "Descrizioni",                                 # Le ἐκφράσεις di statue si citano in italiano come «Descrizioni» (lat. D…
    "tlg7000.tlg001":      "Antologia Palatina",                          # In italiano la raccolta si cita sempre «Antologia Palatina»; «Volume V»…
}

# Originali da correggere: il catalogo della fonte porta spesso il titolo
# convenzionale LATINO su un'opera greca (Arriano «Anabasis», Ippocrate
# «Iusiurandum»), che promette l'originale e dà una traduzione.
ORIG_RESTO = {
    "stoa0040.stoa011":    "Epistulae",
    "stoa0054.stoa006":    "Historia ecclesiastica gentis Anglorum",
    "stoa0162.stoa004":    "Epistulae",
    "stoa0238.stoa004":    "Liber Cathemerinon",
    "stoa0261.stoa0002":   "Epistulae, libri VIII-IX",
    "tlg0017.tlg007":      "Περὶ τοῦ Ἀπολλοδώρου κλήρου",
    "tlg0017.tlg012":      "Ὑπὲρ Εὐφιλήτου",
    "tlg0030.tlg004":      "Ὑπὲρ Εὐξενίππου εἰσαγγελίας ἀπολογία πρὸς Πολύευκτον",
    "tlg0031.tlg001":      "Κατὰ Ματθαῖον",
    "tlg0031.tlg002":      "Κατὰ Μᾶρκον",
    "tlg0031.tlg003":      "Κατὰ Λουκᾶν",
    "tlg0031.tlg004":      "Κατὰ Ἰωάννην",
    "tlg0031.tlg005":      "Πράξεις Ἀποστόλων",
    "tlg0031.tlg006":      "Πρὸς Ῥωμαίους",
    "tlg0031.tlg007":      "Πρὸς Κορινθίους Α΄",
    "tlg0031.tlg008":      "Πρὸς Κορινθίους Β΄",
    "tlg0031.tlg009":      "Πρὸς Γαλάτας",
    "tlg0031.tlg010":      "Πρὸς Ἐφεσίους",
    "tlg0031.tlg011":      "Πρὸς Φιλιππησίους",
    "tlg0031.tlg012":      "Πρὸς Κολοσσαεῖς",
    "tlg0031.tlg013":      "Πρὸς Θεσσαλονικεῖς Α΄",
    "tlg0031.tlg014":      "Πρὸς Θεσσαλονικεῖς Β΄",
    "tlg0031.tlg015":      "Πρὸς Τιμόθεον Α΄",
    "tlg0031.tlg016":      "Πρὸς Τιμόθεον Β΄",
    "tlg0031.tlg017":      "Πρὸς Τίτον",
    "tlg0031.tlg018":      "Πρὸς Φιλήμονα",
    "tlg0031.tlg019":      "Πρὸς Ἑβραίους",
    "tlg0031.tlg021":      "Πέτρου Α΄",
    "tlg0031.tlg022":      "Πέτρου Β΄",
    "tlg0031.tlg023":      "Ἰωάννου Α΄",
    "tlg0031.tlg024":      "Ἰωάννου Β΄",
    "tlg0031.tlg025":      "Ἰωάννου Γ΄",
    "tlg0031.tlg026":      "Ἰούδα",
    "tlg0031.tlg027":      "Ἀποκάλυψις Ἰωάννου",
    "tlg0036.tlg001":      "Ἀδώνιδος ἐπιτάφιος",
    "tlg0057.tlg010":      "Περὶ φυσικῶν δυνάμεων",
    "tlg0074.tlg001":      "Ἀλεξάνδρου ἀνάβασις",
    "tlg0081.tlg003":      "Περὶ Λυσίου",
    "tlg0081.tlg004":      "Περὶ Ἰσοκράτους",
    "tlg0081.tlg005":      "Περὶ Ἰσαίου",
    "tlg0081.tlg006":      "Περὶ τῆς Δημοσθένους λέξεως",
    "tlg0081.tlg007":      "Περὶ τῶν ἀρχαίων ῥητόρων (τοῦ β΄ λόγου λείψανα)",
    "tlg0081.tlg010":      "Περὶ Θουκυδίδου",
    "tlg0081.tlg011":      "Περὶ τῶν Θουκυδίδου ἰδιωμάτων πρὸς Ἀμμαῖον",
    "tlg0284.tlg005":      "Ἡρακλῆς",
    "tlg0284.tlg008":      "Εἰς τὸν Σάραπιν",
    "tlg0284.tlg009":      "Εἰς βασιλέα",
    "tlg0284.tlg011":      "Εἰς Ἐτεωνέα ἐπικήδειος",
    "tlg0284.tlg022":      "Προσφωνητικὸς Σμυρναϊκός",
    "tlg0284.tlg033":      "Λευκτρικὸς Α΄ (ὑπὲρ Λακεδαιμονίων πρῶτος)",
    "tlg0284.tlg034":      "Λευκτρικὸς Β΄ (ὑπὲρ Θηβαίων πρῶτος)",
    "tlg0284.tlg035":      "Λευκτρικὸς Γ΄ (ὑπὲρ Λακεδαιμονίων δεύτερος)",
    "tlg0284.tlg036":      "Λευκτρικὸς Δ΄ (ὑπὲρ Θηβαίων δεύτερος)",
    "tlg0284.tlg037":      "Λευκτρικὸς Ε΄ (ὑπὲρ μηδετέροις βοηθεῖν)",
    "tlg0284.tlg038":      "Συμμαχικὸς Α΄",
    "tlg0284.tlg039":      "Συμμαχικὸς Β΄ (πρὸς Θηβαίους περὶ τῆς συμμαχίας)",
    "tlg0284.tlg043":      "Ῥοδιακός",
    "tlg0385.tlg001":      "Ῥωμαϊκὴ ἱστορία",
    "tlg0526.tlg004":      "Ἱστορία Ἰουδαϊκοῦ πολέμου πρὸς Ῥωμαίους",
    "tlg0532.tlg001":      "τὰ κατὰ Λευκίππην καὶ Κλειτοφῶντα",
    "tlg0548.tlg002":      "Ἐπιτομή",
    "tlg0551.tlg002":      "Βασιλική",
    "tlg0551.tlg003":      "Ἰταλική",
    "tlg0551.tlg004":      "Σαυνιτική",
    "tlg0551.tlg005":      "Κελτική",
    "tlg0551.tlg006":      "Σικελικὴ καὶ Νησιωτική",
    "tlg0551.tlg010":      "Νομαδική",
    "tlg0551.tlg011":      "Μακεδονική",
    "tlg0551.tlg017":      "Ἐμφύλια",
    "tlg0554.tlg001":      "Τὰ περὶ Χαιρέαν καὶ Καλλιρρόην",
    "tlg0612.tlg001":      "Λόγοι",
    "tlg0627.tlg006":      "Ἐπιδημιῶν",
    "tlg0627.tlg013":      "Ὅρκος",
    "tlg0719.tlg001":      "Περὶ αἰτίων καὶ σημείων ὀξέων παθῶν",
    "tlg0719.tlg004":      "Χρονίων νούσων θεραπευτικόν",
    "tlg1389.tlg001":      "Λέξεις τῶν δέκα ῥητόρων",
    "tlg2003.tlg013":      "Ἐπιστολαί",
    "tlg2003.tlg017":      "Κατὰ Γαλιλαίων",
    "tlg2040.tlg004":      "Ἐπιστολαί",
    "tlg2046.tlg001":      "Τὰ μεθ’ Ὅμηρον",
    "tlg2934.tlg066":      "Βαρλαὰμ καὶ Ἰωάσαφ",
    "tlg4029.tlg002":      "Ἀνέκδοτα",
    "tlg4036.tlg023":      "Χρηστομάθεια γραμματική",
    "tlg7000.tlg001":      "Παλατινὴ Ἀνθολογία",
}
