# -*- coding: utf-8 -*-
"""Date di composizione — GENERATO da _gen_opere.py, non modificare a mano.

Curate a mano per il CANONE LICEALE, non per tutte le 1166 opere: per gli autori
minori e i corpora tecnici la data della singola opera non esiste come dato, e
inventarla sarebbe peggio dell'ordine tradizionale.

Ogni voce dice l'anno E COME lo si conosce, che è la parte che conta:
  "certa"  documentata — didascalia teatrale, processo, dedica, lettera
  "circa"  la critica converge, ma per via indiretta
  "fase"   nessuna data: il numero è solo un posto in una successione relativa
           (i tre periodi platonici, la cronologia interna di un corpus)

L'interfaccia stampa l'anno solo per i primi due tipi. Le opere in "fase" si
ordinano ma non mostrano una data, perché stamparla la farebbe passare per tale.

Anni NEGATIVI = avanti Cristo.

617 opere datate — certa 86 · circa 202 · fase 329.
"""

# id opera → (anno, tipo, su che cosa si regge)
DATE = {
    "phi0119.phi001": (-207, "fase", "Nessun appiglio esterno: anno d'ordine dentro il gruppo delle prime-centrali della cron…"),
    "phi0119.phi002": (-212, "fase", "Nessuna didascalia: anno d'ordine in apertura del gruppo delle commedie più antiche (as…"),
    "phi0119.phi003": (-194, "fase", "Nessun riferimento databile: anno d'ordine nel gruppo centrale della cronologia relativ…"),
    "phi0119.phi004": (-189, "circa", "Al v. 214 cita l'Epidicus come già rappresentato; l'accenno ai trionfi asiatici rimanda…"),
    "phi0119.phi005": (-190, "fase", "Nessuna data documentata: anno d'ordine nel gruppo delle ultime commedie secondo la cro…"),
    "phi0119.phi006": (-185, "circa", "I vv. 979-981 presuppongono il senatoconsulto sui Baccanali del 186; essendo Plauto mor…"),
    "phi0119.phi007": (-202, "circa", "Ai vv. 197-202 la guerra contro i Cartaginesi è ancora in corso: la commedia precede Za…"),
    "phi0119.phi008": (-198, "fase", "Nessuna didascalia: anno d'ordine nel gruppo centrale, subito dopo lo Stichus del 200; …"),
    "phi0119.phi009": (-195, "fase", "Nessun appiglio esterno: anno d'ordine nel gruppo centrale, con il vincolo relativo di …"),
    "phi0119.phi010": (-206, "fase", "Nessuna data documentata: anno d'ordine nel gruppo delle prime-centrali della cronologi…"),
    "phi0119.phi011": (-211, "fase", "Nessuna didascalia: anno d'ordine nel gruppo delle commedie più antiche, insieme ad Asi…"),
    "phi0119.phi012": (-205, "circa", "Ai vv. 211-212 l'allusione al poeta 'barbarus' incarcerato è riferita alla prigionia di…"),
    "phi0119.phi013": (-193, "fase", "Nessun elemento databile: anno d'ordine nel gruppo centrale della cronologia relativa; …"),
    "phi0119.phi014": (-196, "fase", "Nessuna didascalia: anno d'ordine nel gruppo centrale; la critica la colloca genericame…"),
    "phi0119.phi015": (-192, "fase", "Nessuna data documentata: anno d'ordine nel gruppo centrale-tardo; le proposte oscillan…"),
    "phi0119.phi016": (-191, "certa", "Didascalia: ludi Megalenses del 191, per la dedica del tempio della Magna Mater, sotto …"),
    "phi0119.phi017": (-204, "fase", "Nessun appiglio esterno: anno d'ordine fra il gruppo antico e quello centrale; parte de…"),
    "phi0119.phi018": (-200, "certa", "Didascalia: ludi plebei del 200, consoli C. Sulpicio e C. Aurelio Cotta; una delle due …"),
    "phi0119.phi019": (-188, "circa", "Nessuna didascalia, ma la commedia appartiene per metrica e tecnica al gruppo delle ult…"),
    "phi0119.phi020": (-187, "fase", "Cicerone (Cato Maior 50) la ricorda accanto al Pseudolus come opera della vecchiaia del…"),
    "phi0134.phi001": (-166, "certa", "Didascalia: ludi Megalenses del 166, consoli M. Claudio Marcello e C. Sulpicio Gallo; p…"),
    "phi0134.phi002": (-163, "certa", "Didascalia: ludi Megalenses del 163, consoli M. Giovenzio Talna e Ti. Sempronio Gracco."),
    "phi0134.phi003": (-161, "certa", "Didascalia: ludi Megalenses del 161, consoli M. Valerio Messalla e C. Fannio Strabone; …"),
    "phi0134.phi004": (-161, "certa", "Didascalia: ludi Romani del 161 (settembre), stessi consoli dell'Eunuchus, rappresentat…"),
    "phi0134.phi005": (-165, "certa", "Didascalia: prima rappresentazione ai ludi Megalenses del 165, interrotta; ripresa fall…"),
    "phi0134.phi006": (-160, "certa", "Didascalia: ludi funebri per L. Emilio Paolo del 160, consoli L. Anicio Gallo e M. Corn…"),
    "phi0448.phi001": (-51, "circa", "Commentarii sulle campagne del 58-52; la critica prevalente pone la pubblicazione unita…"),
    "phi0448.phi002": (-47, "circa", "redazione dopo la campagna d'Alessandria, comunemente 47 a.C. (altri propongono 45 o un…"),
    "phi0472.phi001": (-54, "circa", "liber composto ca. 62-54 a.C.; i carmi databili più bassi (11, sulla spedizione britann…"),
    "phi0474.phi001": (-81, "certa", "causa civile discussa nell'81 davanti al pretore Dolabella: la prima orazione conservata"),
    "phi0474.phi002": (-80, "certa", "processo per parricidio celebrato nell'80, ancora sotto la dittatura sillana"),
    "phi0474.phi003": (-76, "circa", "causa civile collocata di norma nel 76; una linea critica (Axer) la sposta al 66"),
    "phi0474.phi004": (-70, "certa", "dibattimento preliminare per ottenere l'accusa contro Verre, inizio del 70"),
    "phi0474.phi005": (-70, "certa", "actio prima pronunciata nell'agosto del 70; l'actio secunda pubblicata subito dopo la f…"),
    "phi0474.phi006": (-71, "circa", "causa de vi collocata dalla critica tra il 72 e il 71"),
    "phi0474.phi007": (-69, "circa", "difesa dell'ex governatore della Narbonense, datata al 69 (per alcuni 70/69)"),
    "phi0474.phi008": (-69, "circa", "causa privata de vi armata, collocata di norma nel 69"),
    "phi0474.phi009": (-66, "certa", "sostegno alla rogatio Manilia, pronunciata dai rostri nell'anno della pretura, 66"),
    "phi0474.phi010": (-66, "certa", "processo Cluenzio, celebrato nel 66 mentre Cicerone era pretore"),
    "phi0474.phi011": (-63, "certa", "contro la rogatio agraria di Rullo, dal 1 gennaio del 63, anno del consolato"),
    "phi0474.phi012": (-63, "certa", "processo per perduellio intentato a Rabirio nel 63"),
    "phi0474.phi013": (-63, "certa", "pronunciate tra l'8 novembre e il 5 dicembre del 63; redazione pubblicata nel 60"),
    "phi0474.phi014": (-63, "certa", "processo de ambitu del novembre 63, con Cicerone console in carica"),
    "phi0474.phi015": (-62, "certa", "difesa dall'accusa di complicità con Catilina, 62"),
    "phi0474.phi016": (-62, "certa", "causa sulla cittadinanza del poeta di Antiochia, 62"),
    "phi0474.phi017": (-59, "certa", "processo de repetundis contro l'ex pretore d'Asia, 59"),
    "phi0474.phi018": (-57, "certa", "ringraziamento al popolo dopo il rientro dall'esilio, settembre 57"),
    "phi0474.phi019": (-57, "certa", "pronunciata in senato il 5 settembre 57, alla prima seduta dopo il ritorno"),
    "phi0474.phi020": (-57, "certa", "davanti al collegio pontificale il 29 settembre 57, per riavere l'area della casa sul P…"),
    "phi0474.phi021": (-56, "certa", "discorso in senato del 56 sul responso degli aruspici, contro Clodio"),
    "phi0474.phi022": (-56, "certa", "processo de vi a carico di Sestio, marzo 56"),
    "phi0474.phi023": (-56, "certa", "interrogatorio del teste Vatinio dentro il processo Sestio, marzo 56"),
    "phi0474.phi024": (-56, "certa", "pronunciata il 4 aprile 56, durante i Ludi Megalenses"),
    "phi0474.phi025": (-56, "certa", "intervento in senato del giugno 56, dopo gli accordi di Lucca"),
    "phi0474.phi026": (-56, "certa", "causa sulla cittadinanza di Balbo, 56"),
    "phi0474.phi027": (-55, "certa", "invettiva pronunciata in senato nel 55, contro il console del 58"),
    "phi0474.phi028": (-54, "certa", "processo de sodaliciis, 54"),
    "phi0474.phi029": (-54, "certa", "processo de repetundis per la Sardegna, settembre 54"),
    "phi0474.phi030": (-54, "circa", "appendice del processo a Gabinio: datata di norma al 54, da alcuni al 53"),
    "phi0474.phi031": (-52, "certa", "processo per l'uccisione di Clodio, aprile 52; il testo conservato è la redazione scrit…"),
    "phi0474.phi032": (-46, "certa", "ringraziamento a Cesare in senato per la grazia a Marcello, settembre 46"),
    "phi0474.phi033": (-46, "certa", "perorazione davanti a Cesare nel foro, autunno 46"),
    "phi0474.phi034": (-45, "certa", "pronunciata davanti a Cesare nella sua casa, novembre 45"),
    "phi0474.phi035": (-44, "fase", "Le Filippiche non hanno una data: sono 14 orazioni scaglionate dal 2 settembre 44 (I Fi…"),
    "phi0474.phi036": (-84, "circa", "manuale della giovinezza («pueris nobis» dice lui stesso nel De oratore), collocato att…"),
    "phi0474.phi037": (-55, "certa", "dialogo composto e concluso nel 55, annunciato nel carteggio al fratello Quinto"),
    "phi0474.phi038": (-54, "circa", "catechismo retorico per il figlio Marco: la datazione oscilla tra la fine del 54 e il 4…"),
    "phi0474.phi039": (-46, "certa", "storia dell'eloquenza romana scritta nei primi mesi del 46 e dedicata a Bruto"),
    "phi0474.phi040": (-46, "certa", "composto dopo il Brutus, nella seconda metà del 46"),
    "phi0474.phi041": (-46, "circa", "prefazione alla traduzione di Demostene ed Eschine, collocata di norma nel 46; autentic…"),
    "phi0474.phi042": (-44, "certa", "scritto a memoria durante la traversata verso Velia per Trebazio, luglio 44"),
    "phi0474.phi043": (-51, "circa", "iniziato nel 54, pubblicato nel 51 poco prima della partenza per la Cilicia: si dà l'an…"),
    "phi0474.phi045": (-45, "certa", "prima redazione degli Academica (Lucullus), primavera 45"),
    "phi0474.phi046": (-45, "certa", "seconda redazione, riscritta e dedicata a Varrone, estate 45"),
    "phi0474.phi047": (-46, "circa", "operetta dedicata a Bruto, collocata dalla critica nel 46"),
    "phi0474.phi048": (-45, "certa", "terminato nel giugno 45, come attestano le lettere ad Attico"),
    "phi0474.phi049": (-45, "certa", "composte a Tusculo subito dopo il De finibus, estate 45"),
    "phi0474.phi050": (-45, "certa", "scritto nell'estate-autunno del 45; il De divinatione lo cita come già concluso"),
    "phi0474.phi051": (-44, "circa", "Nessuna fonte data la composizione del Cato maior. L'unico dato duro e' il terminus ant…"),
    "phi0474.phi052": (-44, "certa", "dedicato ad Attico dopo il Cato maior, nel corso del 44"),
    "phi0474.phi053": (-44, "certa", "seguito dichiarato del De natura deorum, completato dopo le Idi di marzo del 44"),
    "phi0474.phi054": (-44, "certa", "colloquio con Irzio ambientato a Pozzuoli e scritto nella primavera del 44"),
    "phi0474.phi055": (-44, "certa", "composto per il figlio ad Atene nell'autunno del 44, ultima opera filosofica"),
    "phi0474.phi056": (-52, "fase", "nessuna data di composizione: raccolta postuma curata da Tirone, lettere dal 62 al 43; …"),
    "phi0474.phi057": (-56, "fase", "nessuna data di composizione: carteggio postumo, lettere dal 68 al 44; si dà l'anno med…"),
    "phi0474.phi058": (-57, "fase", "nessuna data di composizione: raccolta postuma, lettere dal 59 al 54; si dà l'anno medi…"),
    "phi0474.phi059": (-43, "certa", "carteggio dell'aprile-luglio 43, l'ultimo anno di vita; l'autenticità di alcune lettere…"),
    "phi0474.phi072": (-45, "circa", "traduzione parziale (27c-47b) del dialogo platonico, collocata nel 45, tra il De natura…"),
    "phi0550.phi001": (-55, "circa", "poema lasciato incompiuto e uscito postumo: Cicerone lo giudica già in una lettera al f…"),
    "phi0620.phi001": (-23, "circa", "quattro libri scaglionati fra il 29-28 a.C. (Monobiblos) e il 16 a.C. (libro IV: l'eleg…"),
    "phi0631.phi001": (-42, "circa", "prima monografia dopo il ritiro dalla politica seguito alla morte di Cesare: composta t…"),
    "phi0631.phi002": (-41, "circa", "seconda monografia, subito dopo il Catilina: datata dalla critica al 41-40 a.C."),
    "phi0631.phi003": (-37, "circa", "annalistica degli anni 78-67, ultima opera: iniziata verso il 39 e interrotta dalla mor…"),
    "phi0660.phi001": (-26, "circa", "libro I pubblicato ca. 27-26 a.C. (l'eleg. I 7 celebra il trionfo aquitanico di Messall…"),
    "phi0660.phi003": (-18, "fase", "non un'opera d'autore ma il Corpus Tibullianum, che aggiunge ai due libri autentici il …"),
    "phi0690.phi001": (-39, "circa", "composte fra il 42 e il 39 a.C. (esproprio delle terre ai veterani dopo Filippi; l'ecl.…"),
    "phi0690.phi002": (-29, "circa", "lavorate dal 37; il finale allude a Ottaviano all'Eufrate, e la Vita Donati riferisce l…"),
    "phi0690.phi003": (-19, "circa", "Il 19 è la morte del poeta, non una data dell'opera: composta dal 29, edita postuma."),
    "phi0893.phi001": (-23, "circa", "Carmina I-III pubblicati insieme nel 23 a.C.; il libro IV segue ca. 13 a.C. su sollecit…"),
    "phi0893.phi002": (-17, "certa", "eseguito ai Ludi saeculares del 17 a.C.; gli Acta ludorum saecularium (CIL VI 32323) re…"),
    "phi0893.phi003": (-30, "circa", "raccolta pubblicata ca. 30 a.C.: l'epodo 9 presuppone Azio (31) e l'epodo 16 la guerra …"),
    "phi0893.phi004": (-35, "circa", "libro I pubblicato ca. 35 a.C., dopo l'ingresso nel circolo di Mecenate (38); libro II …"),
    "phi0893.phi005": (-20, "circa", "libro I pubblicato ca. 20-19 a.C. (l'epist. I 20 data se stessa al consolato di Lollio,…"),
    "phi0893.phi006": (-10, "fase", "datazione contesa senza convergenza (proposte da ca. 24 a ca. 8 a.C.); l'anno non è una…"),
    "phi0914.phi001": (-31, "circa", "Testata dell'intera opera in 142 libri: avviata dopo Azio (fine anni '30 a.C.) e proseg…"),
    "phi0914.phi0011": (-30, "circa", "Libro 1: in 1,19,3 Ottaviano è già «Augusto» (titolo del gennaio 27) e le chiusure di G…"),
    "phi0914.phi00110": (-21, "fase", "Libro 10, chiusura della seconda pentade (guerre sannitiche); l'anno è il posto del lib…"),
    "phi0914.phi00111s": (-20, "fase", "Corrisponde al libro 11, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00112s": (-19, "fase", "Corrisponde al libro 12, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00113s": (-18, "fase", "Corrisponde al libro 13, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00114s": (-17, "fase", "Corrisponde al libro 14, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00115s": (-16, "fase", "Corrisponde al libro 15, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00116s": (-15, "fase", "Corrisponde al libro 16, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00117s": (-14, "fase", "Corrisponde al libro 17, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00118s": (-13, "fase", "Corrisponde al libro 18, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi00119s": (-12, "fase", "Corrisponde al libro 19, perduto e noto solo per riassunto/supplemento: numero d'ordine…"),
    "phi0914.phi0012": (-29, "fase", "Libro 2, dentro la prima pentade pubblicata fra il 27 e il 25 a.C.: solo la pentade è d…"),
    "phi0914.phi00120s": (-11, "fase", "Corrisponde al libro 20, perduto e noto solo per riassunto/supplemento: ultimo posto de…"),
    "phi0914.phi00121": (-10, "fase", "Libro 21, apertura della terza decade (guerra annibalica), composta dopo le prime due p…"),
    "phi0914.phi00122": (-9, "fase", "Libro 22 (Trasimeno e Canne), secondo posto della terza decade: numero d'ordine dentro …"),
    "phi0914.phi00123": (-8, "fase", "Libro 23 (dopo Canne, Capua), terzo posto della terza decade: numero d'ordine dentro la…"),
    "phi0914.phi00124": (-7, "fase", "Libro 24, quarto posto della terza decade: numero d'ordine dentro la decade annibalica."),
    "phi0914.phi00125": (-6, "fase", "Libro 25 (presa di Siracusa), quinto posto della terza decade: numero d'ordine dentro l…"),
    "phi0914.phi00126": (-5, "fase", "Libro 26 (Annibale alle porte, presa di Capua), sesto posto della terza decade: numero …"),
    "phi0914.phi00127": (-4, "fase", "Libro 27 (Metauro), settimo posto della terza decade: numero d'ordine dentro la decade …"),
    "phi0914.phi00128": (-3, "fase", "Libro 28 (fine della guerra in Spagna), ottavo posto della terza decade: numero d'ordine."),
    "phi0914.phi00129": (-2, "fase", "Libro 29 (Scipione in Africa), nono posto della terza decade: numero d'ordine."),
    "phi0914.phi0013": (-28, "fase", "Libro 3, dentro la prima pentade pubblicata fra il 27 e il 25 a.C.: l'anno è il posto d…"),
    "phi0914.phi00130": (-1, "fase", "Libro 30 (Zama), chiusura della terza decade: numero d'ordine, ultima posizione della d…"),
    "phi0914.phi00131": (1, "fase", "Libro 31, apertura della quarta decade (seconda guerra macedonica), redatta dopo la ter…"),
    "phi0914.phi00132": (2, "fase", "Libro 32, secondo posto della quarta decade: numero d'ordine dentro la sezione macedoni…"),
    "phi0914.phi00133": (3, "fase", "Libro 33 (Cinocefale e libertà della Grecia), terzo posto della quarta decade: numero d…"),
    "phi0914.phi00134": (4, "fase", "Libro 34 (abrogazione della lex Oppia, Catone in Spagna), quarto posto della quarta dec…"),
    "phi0914.phi00135": (5, "fase", "Libro 35 (vigilia della guerra contro Antioco), quinto posto della quarta decade: numer…"),
    "phi0914.phi00136": (6, "fase", "Libro 36 (Termopili, guerra siriaca), sesto posto della quarta decade: numero d'ordine."),
    "phi0914.phi00137": (7, "fase", "Libro 37 (Magnesia), settimo posto della quarta decade: numero d'ordine."),
    "phi0914.phi00138": (8, "fase", "Libro 38 (processi degli Scipioni), ottavo posto della quarta decade: numero d'ordine."),
    "phi0914.phi00139": (9, "fase", "Libro 39 (scandalo dei Baccanali), nono posto della quarta decade: numero d'ordine."),
    "phi0914.phi0014": (-27, "fase", "Libro 4, dentro la prima pentade: in 4,20,5-11 compare il nome «Augusto» (dopo il 27 a.…"),
    "phi0914.phi00140": (10, "fase", "Libro 40, chiusura della quarta decade: numero d'ordine, ultima posizione della sezione…"),
    "phi0914.phi00141": (11, "fase", "Libro 41, apertura dell'ultima sezione conservata (41-45), redatta per ultima fra i lib…"),
    "phi0914.phi00142": (12, "fase", "Libro 42 (vigilia della terza guerra macedonica), secondo posto della sezione 41-45: nu…"),
    "phi0914.phi00143": (13, "fase", "Libro 43, terzo posto della sezione 41-45: numero d'ordine nella successione dei libri …"),
    "phi0914.phi00144": (14, "fase", "Libro 44 (Pidna), quarto posto della sezione 41-45: numero d'ordine."),
    "phi0914.phi00145": (15, "fase", "Libro 45 (trionfo di Emilio Paolo, 167 a.C.), ultimo libro conservato: numero d'ordine,…"),
    "phi0914.phi0015": (-26, "fase", "Libro 5 (presa di Veio e Galli), chiusura della prima pentade pubblicata fra il 27 e il…"),
    "phi0914.phi0016": (-25, "fase", "Libro 6, apertura della seconda pentade, successiva alla prima e anteriore alla terza d…"),
    "phi0914.phi0017": (-24, "fase", "Libro 7, secondo posto della seconda pentade: numero d'ordine dentro la successione dei…"),
    "phi0914.phi0018": (-23, "fase", "Libro 8 (guerre sannitiche, devotio di Decio Mure), terzo posto della seconda pentade: …"),
    "phi0914.phi0019": (-22, "fase", "Libro 9 (Forche Caudine), quarto posto della seconda pentade: numero d'ordine."),
    "phi0914.phi001fr": (16, "fase", "Frammenti dei libri perduti (soprattutto il l. 91 sulla guerra sertoriana, più citazion…"),
    "phi0917.phi001": (63, "circa", "iniziato verso il 61; i primi tre libri circolano nel 62-63, prima della rottura con Ne…"),
    "phi0959.phi001": (-16, "circa", "esordio del poeta: prima edizione in cinque libri intorno al 16 a.C., ridotta poi dallo…"),
    "phi0959.phi002": (-10, "circa", "le epistole singole (1-15) sono già citate in Amores II 18 e vanno quindi agli anni ca.…"),
    "phi0959.phi003": (-3, "fase", "nessuna data propria: unico appiglio è la citazione in Ars amatoria III 205-206, che la…"),
    "phi0959.phi004": (-1, "circa", "libri I-II ca. 1 a.C.: Ars I 171 ricorda la naumachia di Augusto del 2 a.C. e I 177-228…"),
    "phi0959.phi005": (1, "circa", "seguito immediato dell'Ars, cui rinvia esplicitamente: 1-2 d.C."),
    "phi0959.phi006": (8, "circa", "composte fra il 2 e l'8 d.C.; il poeta stesso (Tristia I 7) dice di averle lasciate non…"),
    "phi0959.phi007": (9, "fase", "opera a composizione lunga e spezzata, senza un anno di pubblicazione: avviata ca. 4 d.…"),
    "phi0959.phi008": (10, "circa", "cinque libri composti quasi anno per anno durante il viaggio e i primi anni di Tomi, fr…"),
    "phi0959.phi009": (14, "circa", "libri I-III pubblicati insieme nel 13 d.C. (III 4 allude al trionfo pannonico di Tiberi…"),
    "phi0959.phi010": (12, "circa", "invettiva scritta in esilio, comunemente assegnata al 10-12 d.C.: non compare fra le op…"),
    "phi0969.phi001": (62, "circa", "sei satire composte negli anni Cinquanta e pubblicate postume da Cesio Basso subito dop…"),
    "phi0972.phi001": (64, "circa", "ambientazione e lingua neroniane; identificazione tradizionale dell'autore con il Petro…"),
    "phi0972.phi001f": (64, "circa", "frammenti tramandati a parte ma appartenenti alla stessa opera: stessa datazione neroni…"),
    "phi1002.phi001": (95, "circa", "Quintiliano dichiara poco piu di due anni di lavoro dopo il ritiro dall'insegnamento; l…"),
    "phi1017.phi001": (52, "fase", "Nessun aggancio esterno per le tragedie: numero d'ordine dentro la cronologia relativa …"),
    "phi1017.phi002": (51, "fase", "Numero d'ordine nel gruppo centrale della cronologia relativa di Fitch (Medea, Troades,…"),
    "phi1017.phi003": (65, "fase", "Gruppo tardo della cronologia relativa di Fitch (con il Tieste); dramma incompiuto, per…"),
    "phi1017.phi004": (50, "fase", "Numero d'ordine nel gruppo centrale di Fitch (Medea, Troades, Hercules furens): nessuna…"),
    "phi1017.phi005": (46, "fase", "Numero d'ordine nel gruppo iniziale di Fitch (Agamennone, Fedra, Edipo): metrica e trat…"),
    "phi1017.phi006": (47, "fase", "Numero d'ordine nel gruppo iniziale di Fitch (Agamennone, Fedra, Edipo); l'ordine dentr…"),
    "phi1017.phi007": (45, "fase", "Numero d'ordine nel gruppo iniziale della cronologia relativa di Fitch: primo scaglione…"),
    "phi1017.phi008": (61, "fase", "Gruppo tardo di Fitch (Tieste, Fenicie): verso piu elaborato e struttura piu ampia; l'a…"),
    "phi1017.phi009": (80, "fase", "Trasmessa nel corpus senecano ma giudicata dalla critica prevalente spuria: imitazione …"),
    "phi1017.phi010": (72, "fase", "Praetexta anonima non di Seneca: presuppone la morte di Nerone (68), che preannuncia; l…"),
    "phi1017.phi011": (54, "circa", "Satira sulla morte e apoteosi di Claudio, avvenuta il 13 ottobre 54: composta subito do…"),
    "phi1017.phi013": (62, "circa", "Opera in sette libri elaborata a lungo fra il 56 e il 64; i libri finali risalgono agli…"),
    "phi1017.phi014": (56, "circa", "Clem. 1,9,1 dice che Nerone ha da poco compiuto i diciotto anni (nato 15 dic. 37): fine…"),
    "phi1017.phi015": (64, "circa", "Raccolta scritta dopo il ritiro dalla vita pubblica (62) fino alla morte (65); riferime…"),
    "phi1212.phi001": (158, "circa", "Anno dedotto dai fasti d'Africa (Avito 157/8, Massimo 158/9): convergenza, non documento."),
    "phi1212.phi002": (175, "fase", "nessuna data: il solo argomento e' negativo (l'Apologia del 158 non ne fa cenno, il che…"),
    "phi1212.phi003": (165, "circa", "antologia di brani estratti dalle declamazioni cartaginesi: i pezzi datati nominano il …"),
    "phi1276.phi001": (118, "circa", "cinque libri pubblicati a distanza: il I dopo la condanna di Mario Prisco (100), verso …"),
    "phi1294.phi002": (92, "circa", "i dodici libri escono a cadenza quasi annuale dall'86 (libro I) al 101/102 (libro XII, …"),
    "phi1318.phi001": (107, "circa", "i nove libri di lettere uscirono a scaglioni fra il 100 e il 109, come mostrano gli eve…"),
    "phi1348.abo011": (119, "fase", "Numero d'ordine, non data: libro I del De vita Caesarum, opera unitaria dedicata a Sett…"),
    "phi1348.abo012": (120, "fase", "Numero d'ordine: libro II del De vita Caesarum, entro il primo blocco pubblicato negli …"),
    "phi1348.abo013": (121, "fase", "Numero d'ordine: libro III del De vita Caesarum, primo blocco giulio-claudio pubblicato…"),
    "phi1348.abo014": (122, "fase", "Numero d'ordine: libro IV del De vita Caesarum, primo blocco giulio-claudio pubblicato …"),
    "phi1348.abo015": (123, "fase", "Numero d'ordine: libro V del De vita Caesarum; l'uso diretto dei documenti d'archivio s…"),
    "phi1348.abo016": (124, "fase", "Numero d'ordine: libro VI del De vita Caesarum, chiusura della serie giulio-claudia; ne…"),
    "phi1348.abo017": (125, "fase", "Numero d'ordine dentro il libro VII (Galba, Otone, Vitellio), pubblicato dopo il primo …"),
    "phi1348.abo018": (126, "fase", "Numero d'ordine dentro il libro VII del De vita Caesarum: la successione segue l'ordine…"),
    "phi1348.abo019": (127, "fase", "Numero d'ordine dentro il libro VII del De vita Caesarum, terza e ultima Vita del libro."),
    "phi1348.abo020": (128, "fase", "Numero d'ordine dentro il libro VIII (i Flavi), l'ultimo dell'opera, ritenuto composto …"),
    "phi1348.abo021": (129, "fase", "Numero d'ordine dentro il libro VIII del De vita Caesarum: nessuna data propria, solo l…"),
    "phi1348.abo022": (130, "fase", "Numero d'ordine: ultima Vita del libro VIII e dell'opera; l'anno chiude la successione,…"),
    "phi1351.phi001": (98, "circa", "Il proemio (Agr. 3) saluta il principato appena inaugurato di Nerva e Traiano: composto…"),
    "phi1351.phi002": (98, "certa", "Germ. 37,2 conta gli anni delle guerre germaniche fino al secondo consolato di Traiano:…"),
    "phi1351.phi003": (102, "circa", "Dedicato a Fabio Giusto, console suffetto nel 102; la scena e ambientata nel 75 (sesto …"),
    "phi1351.phi004": (107, "circa", "In corso di stesura quando Plinio (epist. 6,16 e 6,20 sul Vesuvio; 7,33) gli invia mate…"),
    "phi1351.phi005": (117, "circa", "Ultima opera, successiva alle Storie; Ann. 2,61 allude alla massima estensione dell'imp…"),
    "stoa0040.stoa011": (408, "fase", "selezione, non opera pubblicata: le lettere si distendono dal ritiro di Cassiciaco (386…"),
    "stoa0162.stoa004": (395, "fase", "selezione da un epistolario mai pubblicato unitariamente: le 154 lettere vanno dagli an…"),
    "stoa0255.stoa004": (49, "circa", "Dedicato a Pompeo Paolino, prefetto dell'annona: datazione contesa fra il 49 (rientro d…"),
    "stoa0255.stoa006": (42, "circa", "Scritta dalla Corsica per consolare la madre della relegazione dell'autore: primi tempi…"),
    "stoa0255.stoa007": (40, "circa", "Il piu antico dei dialoghi: Marcia e figlia di Cremuzio Cordo, i cui libri furono riabi…"),
    "stoa0255.stoa008": (43, "circa", "Scritta dall'esilio corso al liberto Polibio; allude alla spedizione britannica di Clau…"),
    "stoa0255.stoa009": (53, "fase", "Primo dei tre dialoghi ad Anneo Sereno; nessun aggancio esterno, Griffin lo colloca gen…"),
    "stoa0255.stoa010": (41, "circa", "Rivolta al fratello col nome di Novato, anteriore all'adozione; gli exempla su Caligola…"),
    "stoa0255.stoa011": (60, "fase", "Dialogo mutilo, terzo e ultimo della serie a Sereno (morto verso il 62-63); la critica …"),
    "stoa0255.stoa012": (63, "fase", "Dedicato a Lucilio come le Lettere: la critica prevalente lo assegna alle opere ultime …"),
    "stoa0255.stoa013": (59, "fase", "Secondo dialogo a Sereno; nessuna data documentata, la critica lo pone fra il De consta…"),
    "stoa0255.stoa014": (58, "circa", "Rivolta al fratello col nome adottivo di Gallione (dopo il 52); l'autodifesa sulla ricc…"),
    "tlg0001.tlg001": (-250, "circa", "composte ad Alessandria negli anni legati alla direzione della Biblioteca (ca. 260-246)…"),
    "tlg0003.tlg001": (-400, "circa", "composta durante la guerra e rimasta interrotta al 411; II,65 presuppone la sconfitta d…"),
    "tlg0005.tlg001": (-272, "circa", "gli idilli databili sono gli encomi: il 16 a Ierone II di Siracusa (275/274) e il 17 a …"),
    "tlg0005.tlg002": (-265, "fase", "nessuna data: raccolta antologica, in parte spuria, formatasi per aggregazione; l'anno …"),
    "tlg0006.tlg001": (-409, "fase", "dramma satiresco senza didascalia; le soluzioni metriche e gli echi di Tesmoforiazuse (…"),
    "tlg0006.tlg002": (-438, "certa", "didascalia: Dionisie del 438, quarto dramma della tetralogia con Cretesi, Alcmeone a Ps…"),
    "tlg0006.tlg003": (-431, "certa", "didascalia: Dionisie del 431, arcontato di Pitodoro, con Filottete, Ditti e il satiresc…"),
    "tlg0006.tlg004": (-430, "circa", "nessuna didascalia; il tono antispartano e i riferimenti all'invasione dell'Attica coll…"),
    "tlg0006.tlg005": (-428, "certa", "didascalia: Dionisie del 428, arcontato di Epaminone, primo premio; e il secondo Ippoli…"),
    "tlg0006.tlg006": (-425, "circa", "nessuna didascalia (uno scolio afferma che non fu rappresentata ad Atene); la polemica …"),
    "tlg0006.tlg007": (-424, "circa", "terminus ante quem dalla parodia nelle Nuvole di Aristofane (423); i criteri metrici co…"),
    "tlg0006.tlg008": (-423, "circa", "nessuna didascalia; l'episodio del rifiuto ateniese dei caduti allude alla battaglia di…"),
    "tlg0006.tlg009": (-416, "fase", "priva di didascalia; la percentuale di soluzioni nel trimetro (Cropp-Fick) la colloca i…"),
    "tlg0006.tlg010": (-413, "fase", "priva di didascalia; la statistica delle soluzioni la assegna al 413 circa (fascia 418-…"),
    "tlg0006.tlg011": (-415, "certa", "didascalia: Dionisie del 415, trilogia troiana Alessandro-Palamede-Troiane con il satir…"),
    "tlg0006.tlg012": (-420, "fase", "nessun dato esterno sicuro; i criteri metrici di Zielinski-Cropp-Fick la pongono nella …"),
    "tlg0006.tlg013": (-414, "fase", "priva di didascalia; tre criteri metrici la pongono dopo le Troiane e la statistica di …"),
    "tlg0006.tlg014": (-412, "certa", "lo scolio alle Tesmoforiazuse di Aristofane (v. 1012) dice che Elena fu rappresentata l…"),
    "tlg0006.tlg015": (-410, "circa", "la hypothesis la ricorda rappresentata con Enomao e Crisippo; scoli e criteri metrici c…"),
    "tlg0006.tlg016": (-408, "certa", "lo scolio alle Rane di Aristofane (v. 279) data la rappresentazione all'arcontato di Di…"),
    "tlg0006.tlg017": (-405, "circa", "Stessa produzione postuma della voce tlg0006.tlg018, quindi stesso difetto probatorio: …"),
    "tlg0006.tlg018": (-405, "circa", "Per la trilogia postuma (Ifigenia in Aulide, Alcmeone a Corinto, Baccanti) NON esiste a…"),
    "tlg0006.tlg019": (-450, "fase", "opera di paternita contestata: la critica moderna la assegna in prevalenza al IV secolo…"),
    "tlg0007.tlg001": (120, "fase", "Vite parallele, coppia finale (23ª) della successione ricostruita: il proemio dichiara …"),
    "tlg0007.tlg002": (120, "fase", "Romano della coppia Teseo-Romolo, ultima della successione ricostruita delle Vite: solo…"),
    "tlg0007.tlg003": (120, "fase", "Sincrisi della coppia Teseo-Romolo: stessa posizione della coppia, ultima nella success…"),
    "tlg0007.tlg004": (119, "fase", "Il proemio del Teseo presuppone già composta la coppia Licurgo-Numa: penultima (22ª) ne…"),
    "tlg0007.tlg005": (119, "fase", "Romano della coppia Licurgo-Numa, 22ª nella successione ricostruita, immediatamente pri…"),
    "tlg0007.tlg006": (119, "fase", "Sincrisi della coppia Licurgo-Numa, 22ª nella successione ricostruita"),
    "tlg0007.tlg007": (118, "fase", "Coppia tarda (21ª) nella successione ricostruita delle Vite; nessun aggancio cronologic…"),
    "tlg0007.tlg008": (118, "fase", "Romano della coppia Solone-Publicola, 21ª nella successione ricostruita"),
    "tlg0007.tlg009": (118, "fase", "Sincrisi della coppia Solone-Publicola, 21ª nella successione ricostruita"),
    "tlg0007.tlg010": (114, "fase", "Coppia 17ª nella successione ricostruita delle Vite: solo ordine relativo, nessuna data"),
    "tlg0007.tlg011": (114, "fase", "Romano della coppia Temistocle-Camillo (priva di sincrisi), 17ª nella successione ricos…"),
    "tlg0007.tlg012": (107, "fase", "Ancoraggio interno: Pericle 2 dichiara che questo è il decimo libro delle Vite parallel…"),
    "tlg0007.tlg013": (107, "fase", "Romano del decimo libro (Pericle-Fabio) per dichiarazione interna di Pericle 2"),
    "tlg0007.tlg014": (107, "fase", "Sincrisi del decimo libro delle Vite parallele (Pericle-Fabio)"),
    "tlg0007.tlg015": (108, "fase", "Coppia 11ª nella successione ricostruita; la critica colloca la coppia dei caratteri am…"),
    "tlg0007.tlg016": (108, "fase", "Romano della coppia Alcibiade-Coriolano, 11ª nella successione ricostruita"),
    "tlg0007.tlg017": (108, "fase", "Sincrisi della coppia Alcibiade-Coriolano, 11ª nella successione ricostruita"),
    "tlg0007.tlg018": (103, "fase", "Coppia 6ª nella successione ricostruita, subito dopo il quinto libro (Demostene-Cicerone)"),
    "tlg0007.tlg019": (103, "fase", "Romano della coppia Timoleonte-Emilio Paolo, 6ª nella successione ricostruita"),
    "tlg0007.tlg020": (103, "fase", "Sincrisi della coppia Timoleonte-Emilio Paolo, 6ª nella successione ricostruita"),
    "tlg0007.tlg021": (100, "fase", "Coppia 3ª nella successione ricostruita, nel primo gruppo delle Vite avviato sotto Traiano"),
    "tlg0007.tlg022": (100, "fase", "Romano della coppia Pelopida-Marcello, 3ª nella successione ricostruita"),
    "tlg0007.tlg023": (100, "fase", "Sincrisi della coppia Pelopida-Marcello, 3ª nella successione ricostruita"),
    "tlg0007.tlg024": (111, "fase", "Coppia 14ª nella successione ricostruita, dopo il dodicesimo libro (Dione-Bruto)"),
    "tlg0007.tlg025": (111, "fase", "Romano della coppia Aristide-Catone il Censore, 14ª nella successione ricostruita"),
    "tlg0007.tlg026": (111, "fase", "Sincrisi della coppia Aristide-Catone, 14ª nella successione ricostruita"),
    "tlg0007.tlg027": (106, "fase", "Coppia 9ª nella successione ricostruita, subito prima del decimo libro (Pericle-Fabio)"),
    "tlg0007.tlg028": (106, "fase", "Romano della coppia Filopemene-Flaminino, 9ª nella successione ricostruita"),
    "tlg0007.tlg029": (106, "fase", "Sincrisi della coppia Filopemene-Flaminino, 9ª nella successione ricostruita"),
    "tlg0007.tlg030": (117, "fase", "Coppia 20ª nella successione ricostruita, priva di sincrisi: fra le tarde"),
    "tlg0007.tlg031": (117, "fase", "Romano della coppia Pirro-Mario (priva di sincrisi), 20ª nella successione ricostruita"),
    "tlg0007.tlg032": (101, "fase", "Coppia 4ª nella successione ricostruita, subito prima del quinto libro (Demostene-Cicer…"),
    "tlg0007.tlg033": (101, "fase", "Romano della coppia Lisandro-Silla, 4ª nella successione ricostruita"),
    "tlg0007.tlg034": (101, "fase", "Sincrisi della coppia Lisandro-Silla, 4ª nella successione ricostruita"),
    "tlg0007.tlg035": (99, "fase", "Coppia 2ª nella successione ricostruita: apre di fatto la serie, dopo la perduta Epamin…"),
    "tlg0007.tlg036": (99, "fase", "Romano della coppia Cimone-Lucullo, 2ª nella successione ricostruita e fra le più antiche"),
    "tlg0007.tlg037": (99, "fase", "Sincrisi della coppia Cimone-Lucullo, 2ª nella successione ricostruita"),
    "tlg0007.tlg038": (113, "fase", "Coppia 16ª nella successione ricostruita, dopo il dodicesimo libro"),
    "tlg0007.tlg039": (113, "fase", "Romano della coppia Nicia-Crasso, 16ª nella successione ricostruita"),
    "tlg0007.tlg040": (113, "fase", "Sincrisi della coppia Nicia-Crasso, 16ª nella successione ricostruita"),
    "tlg0007.tlg041": (105, "fase", "Coppia 8ª nella successione ricostruita delle Vite (greco della coppia Sertorio-Eumene)"),
    "tlg0007.tlg042": (105, "fase", "Romano della coppia Sertorio-Eumene, 8ª nella successione ricostruita"),
    "tlg0007.tlg043": (105, "fase", "Sincrisi della coppia Sertorio-Eumene, 8ª nella successione ricostruita"),
    "tlg0007.tlg044": (116, "fase", "Coppia 19ª nella successione ricostruita, fra le tarde"),
    "tlg0007.tlg045": (116, "fase", "Romano della coppia Agesilao-Pompeo, 19ª nella successione ricostruita"),
    "tlg0007.tlg046": (116, "fase", "Sincrisi della coppia Agesilao-Pompeo, 19ª nella successione ricostruita"),
    "tlg0007.tlg047": (115, "fase", "Coppia 18ª nella successione ricostruita, priva di sincrisi; il proemio programmatico (…"),
    "tlg0007.tlg048": (115, "fase", "Romano della coppia Alessandro-Cesare (priva di sincrisi), 18ª nella successione ricost…"),
    "tlg0007.tlg049": (104, "fase", "Coppia 7ª nella successione ricostruita, priva di sincrisi"),
    "tlg0007.tlg050": (104, "fase", "Romano della coppia Focione-Catone Uticense (priva di sincrisi), 7ª nella successione r…"),
    "tlg0007.tlg051": (112, "fase", "Coppia quadrupla, 15ª nella successione ricostruita delle Vite"),
    "tlg0007.tlg052": (112, "fase", "Romani della coppia quadrupla Agide-Cleomene / Gracchi, 15ª nella successione ricostruita"),
    "tlg0007.tlg053": (112, "fase", "Sincrisi della coppia quadrupla Agide-Cleomene / Gracchi, 15ª nella successione ricostr…"),
    "tlg0007.tlg054": (102, "fase", "Ancoraggio interno: Demostene 3 dichiara che questo è il quinto libro delle Vite parall…"),
    "tlg0007.tlg055": (102, "fase", "Romano del quinto libro (Demostene-Cicerone) per dichiarazione interna di Demostene 3"),
    "tlg0007.tlg056": (102, "fase", "Sincrisi del quinto libro delle Vite parallele (Demostene-Cicerone)"),
    "tlg0007.tlg057": (110, "fase", "Coppia 13ª nella successione ricostruita; il proemio la presenta come coppia «negativa»…"),
    "tlg0007.tlg058": (110, "fase", "Romano della coppia Demetrio-Antonio, 13ª nella successione ricostruita"),
    "tlg0007.tlg059": (110, "fase", "Sincrisi della coppia Demetrio-Antonio, 13ª nella successione ricostruita"),
    "tlg0007.tlg060": (109, "fase", "Ancoraggio interno: Dione 2 dichiara che questo è il dodicesimo libro delle Vite parall…"),
    "tlg0007.tlg061": (109, "fase", "Romano del dodicesimo libro (Dione-Bruto) per dichiarazione interna di Dione 2"),
    "tlg0007.tlg062": (109, "fase", "Sincrisi del dodicesimo libro delle Vite parallele (Dione-Bruto)"),
    "tlg0007.tlg063": (121, "fase", "Vita non appaiata, dedicata a Policrate di Sicione e ai suoi figli: la critica la collo…"),
    "tlg0007.tlg064": (122, "fase", "Vita non appaiata, tramandata con l'Arato e con esso assegnata agli ultimissimi anni; n…"),
    "tlg0007.tlg065": (96, "fase", "Superstite della serie dei Cesari, di fattura meno elaborata: la critica la colloca pri…"),
    "tlg0007.tlg066": (97, "fase", "Seconda superstite della serie dei Cesari, anteriore alle Vite parallele; ordine intern…"),
    "tlg0007.tlg067": (85, "fase", "Pseudo-plutarcheo per la critica corrente; collocato qui perché la tradizione lo trasme…"),
    "tlg0007.tlg068": (89, "fase", "Scritto pedagogico indirizzato a un amico romano per l'educazione dei figli: fase dell'…"),
    "tlg0007.tlg069": (90, "fase", "Indirizzato a Nicandro appena assunta la toga virile: stessa fase pedagogica del De aud…"),
    "tlg0007.tlg070": (101, "fase", "Dedicato a Filopappo, principe di Commagene attivo ad Atene fino alla morte (verso il 1…"),
    "tlg0007.tlg071": (100, "fase", "Dedicato a Sosio Senecione, lo stesso destinatario delle Vite: fase matura, contemporan…"),
    "tlg0007.tlg072": (102, "fase", "Dedicato a Cornelio Pulcro, funzionario romano in Acaia: fase matura sotto Traiano, sen…"),
    "tlg0007.tlg073": (77, "fase", "Breve pezzo epidittico d'impianto scolastico: la critica lo assegna al gruppo delle dec…"),
    "tlg0007.tlg074": (74, "fase", "Declamazione brevissima a tesi: apre il gruppo degli esercizi retorici giovanili, anter…"),
    "tlg0007.tlg075": (75, "fase", "Diatriba brevissima gemella del De fortuna: stesso gruppo delle declamazioni giovanili"),
    "tlg0007.tlg076": (86, "fase", "Autenticità discussa (per molti esercizio consolatorio di scuola, non plutarcheo); la t…"),
    "tlg0007.tlg077": (99, "fase", "Dialogo dedicato a Zeussippo e Moschione: fase matura, senza alcun aggancio cronologico"),
    "tlg0007.tlg078": (91, "fase", "Scritto per le nozze di Polliano ed Euridice, allievi di Plutarco: fase dell'insegnamen…"),
    "tlg0007.tlg079": (93, "fase", "Dialogo simposiale d'ambientazione arcaica, che la critica pone prima delle Questioni c…"),
    "tlg0007.tlg080": (81, "fase", "Diatriba d'impianto retorico, assegnata dalla critica al gruppo giovanile (il tono cont…"),
    "tlg0007.tlg081": (100, "fase", "La raccolta è preceduta da una lettera dedicatoria a Traiano (autenticità dell'epistola…"),
    "tlg0007.tlg082": (106, "fase", "Raccolta gnomica connessa al lavoro documentario sulle Vite spartane: fase matura, ness…"),
    "tlg0007.tlg082a": (106, "fase", "Appendice laconica di autenticità discussa (per molti escerto non plutarcheo); tramanda…"),
    "tlg0007.tlg082b": (106, "fase", "Seconda appendice laconica, di autenticità discussa; tramandata con i Detti spartani, d…"),
    "tlg0007.tlg083": (105, "fase", "Dedicato a Clea, sacerdotessa di Delfi, come l'Iside e Osiride: fase matura del sacerdo…"),
    "tlg0007.tlg084a": (104, "fase", "Erudizione antiquaria contemporanea alla raccolta di materiali per le Vite romane; gene…"),
    "tlg0007.tlg084b": (103, "fase", "Gemello greco delle Questioni romane, generalmente ritenuto il più antico dei due"),
    "tlg0007.tlg085": (104, "fase", "Opera spuria (compilazione d'età imperiale avanzata, con fonti fittizie); collocata qui…"),
    "tlg0007.tlg086": (82, "fase", "Declamazione epidittica, forse tenuta a Roma nelle conferenze giovanili: gruppo retoric…"),
    "tlg0007.tlg087": (83, "fase", "Due discorsi epidittici gemelli della Fortuna dei Romani: stesso gruppo di declamazioni…"),
    "tlg0007.tlg088": (84, "fase", "Declamazione a tesi affine ai due discorsi sulla fortuna: gruppo retorico giovanile"),
    "tlg0007.tlg089": (118, "fase", "Dedicato a Clea; ampiezza dottrinale e maturità della teologia delfica lo fanno colloca…"),
    "tlg0007.tlg090": (108, "fase", "Dialogo pitico dedicato a Sarapione, posteriore all'assunzione del sacerdozio delfico (…"),
    "tlg0007.tlg091": (112, "fase", "Dialogo pitico che presuppone la rinascita edilizia del santuario sotto Traiano: genera…"),
    "tlg0007.tlg092": (95, "fase", "Data drammatica fissata attorno all'83/84 dal ritorno di Demetrio dalla Britannia; la c…"),
    "tlg0007.tlg093": (76, "fase", "Breve declamazione superstite in forma mutila: gruppo degli esercizi retorici giovanili"),
    "tlg0007.tlg094": (109, "fase", "Trattato dottrinale antistoico d'impianto platonico-peripatetico: fase matura, prossima…"),
    "tlg0007.tlg095": (97, "fase", "Dialogo con Fundano; la critica (Jones) lo colloca fra il 92 e il 100 senza poterlo fis…"),
    "tlg0007.tlg096": (108, "fase", "Dedicato a Paccio; la carriera del destinatario lo fa porre dopo il 107, senza limite s…"),
    "tlg0007.tlg097": (101, "fase", "Dedicato ai fratelli Avidii Nigrino e Quieto, attivi sotto Traiano: fase matura"),
    "tlg0007.tlg098": (102, "fase", "Gruppo dei trattati etici della maturità, affine al De fraterno amore; nessun appiglio …"),
    "tlg0007.tlg099": (79, "fase", "Frammento di declamazione a tesi, superstite mutilo: gruppo degli esercizi retorici gio…"),
    "tlg0007.tlg100": (80, "fase", "Frammento di declamazione gemello del precedente: gruppo degli esercizi retorici giovanili"),
    "tlg0007.tlg101": (103, "fase", "Trattato etico-diatribico della maturità, primo della serie sui vizi sociali (loquacità…"),
    "tlg0007.tlg102": (104, "fase", "Secondo della serie matura sui vizi sociali, strettamente affine al De garrulitate"),
    "tlg0007.tlg103": (105, "fase", "Terzo della serie matura sui vizi sociali; nessun dato esterno di datazione"),
    "tlg0007.tlg104": (106, "fase", "Quarto della serie matura sui vizi sociali; posizione dedotta dalla contiguità tematica…"),
    "tlg0007.tlg105": (107, "fase", "Ultimo, e mutilo, della serie matura sui vizi sociali"),
    "tlg0007.tlg106": (109, "fase", "Trattato etico-politico indirizzato a un amico romano impegnato nella vita pubblica: fa…"),
    "tlg0007.tlg107": (111, "fase", "Grande dialogo teologico ambientato a Delfi, con il mito di Tespesio: fase matura del s…"),
    "tlg0007.tlg108": (113, "fase", "Opera spuria (manualetto medioplatonico del II secolo); collocata qui perché la tradizi…"),
    "tlg0007.tlg109": (110, "fase", "Dialogo storico-filosofico con cornice tebana: fase matura, senza alcun dato di datazione"),
    "tlg0007.tlg110": (96, "fase", "Consolatoria a un amico bandito da Sardi; la critica la colloca attorno alla fine del r…"),
    "tlg0007.tlg111": (94, "fase", "Lettera occasionata dalla morte della figlioletta Timossena: l'evento non è databile, m…"),
    "tlg0007.tlg112": (110, "fase", "Nove libri dedicati a Sosio Senecione e redatti lungo molti anni: anno centrale convenz…"),
    "tlg0007.tlg113": (112, "fase", "La cornice è affidata al figlio Autobulo, che riferisce un episodio della giovinezza de…"),
    "tlg0007.tlg114": (112, "fase", "Raccolta spuria, tramandata come appendice dell'Erotico: collocata dove la tradizione m…"),
    "tlg0007.tlg115": (105, "fase", "Gruppo degli scritti politici della maturità, in forma di breve declamazione; nessun ag…"),
    "tlg0007.tlg116": (106, "fase", "Stesso gruppo politico del precedente, cui è affine per destinatario e impianto"),
    "tlg0007.tlg117": (117, "fase", "Plutarco vi parla da vecchio, richiamando la propria lunga militanza civica e sacerdota…"),
    "tlg0007.tlg118": (110, "fase", "Indirizzato al giovane Menemaco di Sardi; scritto sotto Traiano, in piena maturità poli…"),
    "tlg0007.tlg119": (111, "fase", "Frammento superstite di un discorso (forse proemio), tramandato accanto ai Precetti pol…"),
    "tlg0007.tlg120": (113, "fase", "Diatriba economico-morale della maturità, affine per tono alla serie sui vizi; nessun d…"),
    "tlg0007.tlg121": (111, "fase", "Compilazione spuria d'età imperiale avanzata; la tradizione la trasmette nel corpus fra…"),
    "tlg0007.tlg122": (107, "fase", "Epitome tarda di un confronto plutarcheo autentico: l'anno colloca l'originale nella fa…"),
    "tlg0007.tlg123": (92, "fase", "Pamphlet polemico d'impianto retorico, che la critica prevalente assegna alla produzion…"),
    "tlg0007.tlg126": (116, "fase", "Dialogo scientifico-escatologico fra i più elaborati del corpus, con mito finale: fase …"),
    "tlg0007.tlg127": (115, "fase", "Indirizzato a Favorino di Arelate, attivo fra Traiano e Adriano: opera degli ultimi anni"),
    "tlg0007.tlg128": (78, "fase", "Declamazione a tesi di autenticità discussa; gruppo degli esercizi retorici giovanili, …"),
    "tlg0007.tlg129": (113, "fase", "Dialogo della maturità, primo tempo del dittico zoologico; nessun aggancio cronologico …"),
    "tlg0007.tlg130": (114, "fase", "Il Grillo, secondo tempo del dittico zoologico, cui è legato per argomento e tecnica di…"),
    "tlg0007.tlg131": (87, "fase", "Declamazione giovanile d'argomento pitagorico, superstite in forma mutila: gruppo retor…"),
    "tlg0007.tlg132": (88, "fase", "Secondo discorso del dittico giovanile sul mangiar carne, anch'esso mutilo"),
    "tlg0007.tlg133": (114, "fase", "Raccolta esegetica di scuola sui dialoghi platonici: fase matura dell'insegnamento, pro…"),
    "tlg0007.tlg134": (117, "fase", "Dedicato ai figli Autobulo e Plutarco ormai adulti: opera degli ultimi anni, vertice de…"),
    "tlg0007.tlg135": (117, "fase", "Riassunto del trattato precedente, tramandato con esso: stessa collocazione, ordine imm…"),
    "tlg0007.tlg136": (116, "fase", "Primo pezzo del gruppo polemico antistoico, che la critica colloca negli ultimi anni pe…"),
    "tlg0007.tlg137": (116, "fase", "Sinossi superstite gemella delle Contraddizioni degli Stoici: stesso gruppo polemico tardo"),
    "tlg0007.tlg138": (117, "fase", "Terzo e più ampio pezzo del gruppo antistoico: stessa fase tarda"),
    "tlg0007.tlg139": (118, "fase", "Primo pezzo del gruppo polemico antiepicureo, assegnato agli ultimi anni per contiguità…"),
    "tlg0007.tlg140": (118, "fase", "Strettamente legato al precedente nello stesso gruppo antiepicureo; l'ordine reciproco …"),
    "tlg0007.tlg141": (119, "fase", "Breve declamazione antiepicurea che chiude il gruppo nella tradizione manoscritta: ulti…"),
    "tlg0010.tlg001": (-403, "circa", "Causa privata successiva alla cacciata dei Trenta: la critica la pone nel 403/2, il più…"),
    "tlg0010.tlg002": (-402, "circa", "Paragraphe fondata sull'amnistia del 403, con richiamo all'arcontato di Senaineto: 402."),
    "tlg0010.tlg003": (-400, "circa", "Causa per percosse ambientata nella democrazia restaurata: 400 ca."),
    "tlg0010.tlg004": (-397, "circa", "Difesa di Alcibiade il Giovane per la vicenda delle quadrighe paterne: 397 ca."),
    "tlg0010.tlg005": (-393, "circa", "La vertenza con il banchiere Pasione presuppone gli anni della guerra corinzia: 393 ca."),
    "tlg0010.tlg006": (-391, "circa", "Causa ereditaria egineta che la critica colloca intorno al 391."),
    "tlg0010.tlg007": (-375, "fase", "Attribuzione discussa (molti la ritengono spuria): la tradizione la colloca tra i paren…"),
    "tlg0010.tlg008": (-390, "circa", "Manifesto programmatico all'apertura della scuola presso il Liceo: 391-390."),
    "tlg0010.tlg009": (-385, "fase", "Nessuna data ricavabile: fase epidittica giovanile della scuola (390-380), in dialogo p…"),
    "tlg0010.tlg010": (-388, "fase", "Come l'Elena, esercizio epidittico degli anni 390-380 in risposta a Policrate: solo ord…"),
    "tlg0010.tlg011": (-380, "circa", "Pubblicato per l'Olimpiade del 380; terminus post quem la pace di Antalcida (386)."),
    "tlg0010.tlg012": (-373, "circa", "Orazione fittizia composta subito dopo la distruzione di Platea a opera dei Tebani (373)."),
    "tlg0010.tlg013": (-374, "circa", "Speculum principis per Nicocle, salito al trono di Salamina di Cipro nel 374/3."),
    "tlg0010.tlg014": (-370, "fase", "Senza appigli diretti: la critica lo pone dopo A Nicocle, dentro la serie ciprica degli…"),
    "tlg0010.tlg015": (-367, "circa", "Encomio funebre per Evagora, morto nel 374/3, per i giochi istituiti dal figlio Nicocle…"),
    "tlg0010.tlg016": (-366, "circa", "Orazione fittizia sulla questione di Messene, dopo il riconoscimento imposto dai Tebani…"),
    "tlg0010.tlg017": (-355, "circa", "Composto alla fine della guerra sociale, quando Atene riconosce l'indipendenza degli al…"),
    "tlg0010.tlg018": (-357, "circa", "Programma di riforma dell'Areopago: la critica oscilla tra il 357, alla vigilia della g…"),
    "tlg0010.tlg019": (-354, "certa", "Isocrate vi dichiara di avere ottantadue anni: 354/3."),
    "tlg0010.tlg020": (-346, "certa", "Scritto immediatamente dopo la pace di Filocrate (346), di cui discute gli esiti."),
    "tlg0010.tlg021": (-339, "fase", "L'opera dichiara essa stessa una composizione distesa e interrotta: Panath. 3 'τοις ετε…"),
    "tlg0010.tlg022": (-368, "circa", "Epistola I, a Dionigi I di Siracusa, dopo la pace del 368 e poco prima della sua morte …"),
    "tlg0010.tlg023": (-359, "circa", "Epistola VI, ai figli di Giasone di Fere, nel turbolento passaggio di potere tessalo: 3…"),
    "tlg0010.tlg024": (-356, "circa", "Epistola IX, ad Archidamo III re di Sparta dal 360/59: la critica converge sul 356."),
    "tlg0010.tlg025": (-350, "circa", "Epistola VIII, richiesta di rimpatrio per il musico Agenore ai reggitori di Mitilene: 3…"),
    "tlg0010.tlg026": (-345, "circa", "Epistola VII, a Timoteo signore di Eraclea Pontica, salito al potere nel 346/5."),
    "tlg0010.tlg027": (-342, "circa", "Epistola II, scritta dopo il ferimento di Filippo in Tracia per dissuaderlo dal rischio…"),
    "tlg0010.tlg028": (-342, "circa", "Epistola V, biglietto per il giovane Alessandro che accompagnava la lettera a Filippo: …"),
    "tlg0010.tlg029": (-340, "circa", "Epistola IV, raccomandazione per Diodoto rivolta ad Antipatro: 340/339."),
    "tlg0010.tlg030": (-338, "circa", "Epistola III, successiva a Cheronea (338), ultimo scritto della tradizione isocratea; a…"),
    "tlg0011.tlg001": (-435, "fase", "nessun dato esterno; la critica prevalente la colloca fra il 440 e il 430 per criteri s…"),
    "tlg0011.tlg002": (-442, "circa", "la hypothesis di Aristofane di Bisanzio lega il successo dell'Antigone all'elezione di …"),
    "tlg0011.tlg003": (-445, "fase", "nessuna didascalia; criteri stilistico-metrici (uso del coro, struttura dittica) la fan…"),
    "tlg0011.tlg004": (-429, "circa", "la descrizione della pestilenza tebana nel prologo e riferita all'epidemia di Atene del…"),
    "tlg0011.tlg005": (-414, "fase", "nessuna didascalia; la vicinanza stilistica e metrica a Filottete (409) e Edipo a Colon…"),
    "tlg0011.tlg006": (-409, "certa", "didascalia: Dionisie del 409, arcontato di Glaucippo, primo premio"),
    "tlg0011.tlg007": (-401, "certa", "composta negli ultimi anni e rappresentata postuma nel 401 dal nipote Sofocle il Giovan…"),
    "tlg0011.tlg008": (-448, "fase", "dramma satiresco noto solo da P.Oxy. 1174 (II sec. d.C.), privo di qualsiasi indizio cr…"),
    "tlg0012.tlg001": (-750, "fase", "poesia orale non databile: si adotta la fascia convenzionale della fissazione del testo…"),
    "tlg0012.tlg002": (-720, "fase", "posteriore all'Iliade secondo la successione relativa comunemente accolta (lingua, tecn…"),
    "tlg0012.tlg003": (-700, "fase", "pseudepigrafi tràditi dalla Vita pseudoerodotea, non di Omero: si collocano in coda al …"),
    "tlg0014.tlg001": (-349, "circa", "prima delle tre Olintiache, tenute mentre Filippo stringe Olinto: la critica converge s…"),
    "tlg0014.tlg002": (-349, "circa", "seconda della serie olintiaca, stessa campagna d'assemblee del 349 (ordine relativo dis…"),
    "tlg0014.tlg003": (-348, "circa", "ultima delle Olintiache, quando la caduta della città è imminente: 349/348"),
    "tlg0014.tlg004": (-351, "circa", "prima orazione del programma antimacedone, dopo le imprese di Filippo in Tracia: consen…"),
    "tlg0014.tlg005": (-346, "circa", "pronunciata pochi mesi dopo la pace di Filocrate e l'ammissione di Filippo all'Anfizion…"),
    "tlg0014.tlg006": (-344, "circa", "legata alle ambascerie nel Peloponneso e alle proteste di Argo e Messene: 344/343"),
    "tlg0014.tlg007": (-342, "circa", "risponde alla proposta di Filippo su Alonneso, 343/342; l'antichità stessa la attribuiv…"),
    "tlg0014.tlg008": (-341, "circa", "difesa dell'operato di Diopite nel Chersoneso: primavera 341"),
    "tlg0014.tlg009": (-341, "circa", "tenuta pochissimo dopo il discorso sul Chersoneso, nella stessa stagione politica del 341"),
    "tlg0014.tlg010": (-340, "circa", "in larga parte tessuta con materiale della III Filippica e del περὶ συντάξεως; autentic…"),
    "tlg0014.tlg011": (-340, "circa", "replica all'ultimatum di Filippo alla vigilia della guerra, 340; quasi unanimemente rit…"),
    "tlg0014.tlg012": (-340, "circa", "documento macedone (o sua rielaborazione) inserito nel corpus: la dichiarazione di guer…"),
    "tlg0014.tlg013": (-350, "circa", "i riferimenti alla contesa per l'orgás megarese la fissano fra 352/1 e 350/49; autentic…"),
    "tlg0014.tlg014": (-354, "circa", "nata dal panico per una presunta spedizione persiana e dalla riforma delle simmorie: 35…"),
    "tlg0014.tlg015": (-351, "circa", "successiva alla repressione persiana di Rodi da parte di Artemisia: la critica oscilla …"),
    "tlg0014.tlg016": (-353, "circa", "ambasceria megalopolitana ad Atene nel conflitto fra Sparta e Tebe: 353/352"),
    "tlg0014.tlg017": (-331, "circa", "contesto della guerra di Agide e delle violazioni della lega di Corinto, 331/330; opera…"),
    "tlg0014.tlg018": (-330, "certa", "pronunciata al processo contro Ctesifonte per la corona, 330: data documentata dalle fonti"),
    "tlg0014.tlg019": (-343, "certa", "pronunciata al processo per prevaricazione contro Eschine, 343: data documentata"),
    "tlg0014.tlg020": (-354, "circa", "causa contro la legge di Leptine sulle immunità: la critica la fissa al 355/354"),
    "tlg0014.tlg021": (-347, "circa", "lo schiaffo di Midia avvenne alle Dionisie del 348 e la probolḗ subito dopo; il discors…"),
    "tlg0014.tlg022": (-355, "circa", "γραφὴ παρανόμων contro il decreto di Androzione: 355/354, primo grande impegno pubblico…"),
    "tlg0014.tlg023": (-352, "circa", "vicende trace di Caridemo e Cersoblepte: 352/351"),
    "tlg0014.tlg024": (-353, "circa", "seguito processuale dell'affare Androzione-Timocrate, ambasceria a Mausolo: 353/352"),
    "tlg0014.tlg025": (-325, "circa", "processo contro il sicofante Aristogitone debitore dello Stato, collocato verso il 325/…"),
    "tlg0014.tlg026": (-324, "fase", "seconda orazione dello stesso dossier, quasi certamente spuria e senza appigli propri: …"),
    "tlg0014.tlg027": (-364, "circa", "processo di Demostene contro i tutori, due anni dopo la maggiore età: arcontato di Timo…"),
    "tlg0014.tlg028": (-364, "circa", "seconda replica nello stesso dibattimento contro Afobo, medesima udienza del 364/363"),
    "tlg0014.tlg029": (-363, "circa", "causa per falsa testimonianza contro Fano, coda del processo ad Afobo: 363/362"),
    "tlg0014.tlg030": (-362, "circa", "δίκη ἐξούλης per recuperare i beni dopo la condanna di Afobo: 362/361"),
    "tlg0014.tlg031": (-362, "circa", "seconda orazione della stessa causa contro Onetore, medesimo dibattimento del 362/361"),
    "tlg0014.tlg032": (-340, "circa", "παραγραφή su un prestito marittimo con la frode navale di Ierone; la critica la colloca…"),
    "tlg0014.tlg033": (-341, "circa", "controversia bancaria e arbitrato con Apaturio di Bisanzio: collocata dagli studiosi in…"),
    "tlg0014.tlg034": (-327, "circa", "allude alla carestia granaria e alle campagne di Alessandro: 327/326"),
    "tlg0014.tlg035": (-341, "circa", "contratto di prestito marittimo per il Ponto citato per esteso; datazione corrente 341/340"),
    "tlg0014.tlg036": (-350, "circa", "paragraphḗ a favore del banchiere Formione, dieci anni dopo la morte di Pasione: 350/349"),
    "tlg0014.tlg037": (-346, "circa", "causa mineraria del Laurio, con arbitrato documentato: la critica la fissa al 346/345"),
    "tlg0014.tlg038": (-346, "circa", "paragraphḗ per prescrizione ventennale su tutela conclusa: gli intervalli interni porta…"),
    "tlg0014.tlg039": (-348, "circa", "prima lite di Mantiteo col fratellastro sull'omonimia: collocata verso il 348"),
    "tlg0014.tlg040": (-345, "circa", "seconda fase della stessa vertenza familiare, alcuni anni dopo la prima: 346/345"),
    "tlg0014.tlg041": (-360, "fase", "nessun indizio cronologico interno; la critica la assegna genericamente alle private gi…"),
    "tlg0014.tlg042": (-329, "circa", "antídosis per la trierarchia con allusioni alla crisi granaria e ai prezzi del grano: a…"),
    "tlg0014.tlg043": (-344, "circa", "causa sull'eredità di Agnia, con lunghe genealogie; la critica la colloca fra 345 e 340"),
    "tlg0014.tlg044": (-365, "circa", "causa sull'eredità di Archiade; gli intervalli genealogici interni la portano agli anni…"),
    "tlg0014.tlg045": (-349, "circa", "causa per falsa testimonianza contro Stefano, seguito immediato del processo Formione d…"),
    "tlg0014.tlg046": (-349, "circa", "seconda orazione dello stesso processo, medesima udienza del 349; l'autenticità demoste…"),
    "tlg0014.tlg047": (-352, "circa", "vicenda trierarchica e recupero degli attrezzi navali, con fatti degli anni 357-355: pr…"),
    "tlg0014.tlg048": (-343, "circa", "lite fra soci sull'eredità di Comone, con riferimenti alla spedizione ateniese in Acarn…"),
    "tlg0014.tlg049": (-361, "circa", "orazione di Apollodoro per un prestito allo stratego Timoteo; i fatti risalgono al 373,…"),
    "tlg0014.tlg050": (-359, "circa", "trierarchia prolungata del 362/361 raccontata dall'interno: il processo segue di qualch…"),
    "tlg0014.tlg051": (-360, "circa", "contesa per la corona trierarchica; collocata dalla critica verso il 360, con qualche d…"),
    "tlg0014.tlg052": (-369, "circa", "orazione di Apollodoro sui conti della banca paterna: i fatti stanno sotto l'arconte So…"),
    "tlg0014.tlg053": (-366, "circa", "apographḗ di Apollodoro sugli schiavi di Aretusio: la critica la colloca verso il 366"),
    "tlg0014.tlg054": (-341, "circa", "il servizio di guarnigione a Panatto ammette due sistemazioni (processo nel 355 o nel 3…"),
    "tlg0014.tlg055": (-351, "fase", "lite di confine per un muro e le acque piovane, priva di qualsiasi appiglio cronologico…"),
    "tlg0014.tlg056": (-322, "circa", "cita Cleomene d'Egitto e la penuria di grano di quegli anni: processo fra 323 e 322"),
    "tlg0014.tlg057": (-345, "circa", "appello contro l'espulsione dal demo nel διαψηφισμός dell'arcontato di Archia, 346/345"),
    "tlg0014.tlg058": (-339, "circa", "ἔνδειξις contro il sicofante Teocrine; la critica oscilla fra il 340/339 e una datazion…"),
    "tlg0014.tlg059": (-342, "circa", "orazione di [Apollodoro]; le allusioni alla guerra con Filippo collocano il processo fr…"),
    "tlg0014.tlg060": (-338, "circa", "L'occasione (funerali pubblici dei caduti di Cheronea, 338) è documentata — Dem. 18,285…"),
    "tlg0014.tlg061": (-335, "fase", "opuscolo epidittico spurio senza alcun appiglio cronologico: anno di puro ordine, in co…"),
    "tlg0014.tlg062": (-343, "fase", "raccolta di esordi d'assemblea messa insieme in età ellenistica da materiale del venten…"),
    "tlg0014.tlg063": (-323, "circa", "le lettere si presentano come scritte dall'esilio (324-322); le prime, ritenute autenti…"),
    "tlg0016.tlg001": (-425, "circa", "l'ultimo evento allusivo è del 430 (guerra archidamica); la critica pone la diffusione …"),
    "tlg0019.tlg001": (-425, "certa", "Didascalia: Lenee del 425, arconte Eutino, messa in scena da Callistrato, primo premio."),
    "tlg0019.tlg002": (-424, "certa", "Didascalia: Lenee del 424, arconte Stratocle, primo premio; prima commedia prodotta dal…"),
    "tlg0019.tlg003": (-423, "certa", "Didascalia: Grandi Dionisie del 423, arconte Isarco, terzo posto; il testo conservato è…"),
    "tlg0019.tlg004": (-422, "certa", "Didascalia: Lenee del 422, arconte Aminia, messa in scena da Filonide, primo premio."),
    "tlg0019.tlg005": (-421, "certa", "Didascalia: Grandi Dionisie del 421, arconte Alceo, secondo premio; alla vigilia della …"),
    "tlg0019.tlg006": (-414, "certa", "Didascalia: Grandi Dionisie del 414, arconte Cabria, messa in scena da Callistrato, sec…"),
    "tlg0019.tlg007": (-411, "certa", "Hypothesis antica: arcontato di Callia (412/411), messa in scena da Callistrato; colloc…"),
    "tlg0019.tlg008": (-411, "circa", "Nessuna didascalia superstite: il 411 si ricava dalle allusioni interne (Euripide vivo …"),
    "tlg0019.tlg009": (-405, "certa", "Didascalia: Lenee del 405, arconte Callia, primo premio; caso eccezionale di replica pe…"),
    "tlg0019.tlg010": (-392, "circa", "Nessuna didascalia: la data si deduce dalle allusioni all'alleanza con Tebe e alla mist…"),
    "tlg0019.tlg011": (-388, "certa", "Il Pluto conservato è il secondo, rappresentato nel 388 sotto l'arconte Antipatro (scol…"),
    "tlg0020.tlg001": (-700, "fase", "nessuna data: l'attività di Esiodo si pone intorno al 700 e la Teogonia precede le Oper…"),
    "tlg0020.tlg002": (-690, "fase", "posteriore alla Teogonia nella successione relativa comunemente accolta (il proemio ne …"),
    "tlg0020.tlg003": (-580, "circa", "opera pseudo-esiodea che continua il Catalogo delle donne: la critica la data ai primi …"),
    "tlg0026.tlg001": (-345, "circa", "Documentato e' l'anno arcontale 346/5, non l'anno civile: l'azione fu intentata sul fin…"),
    "tlg0026.tlg002": (-343, "certa", "Autodifesa al processo per parapresbeia intentato da Demostene nel 343."),
    "tlg0026.tlg003": (-330, "certa", "Processo della Corona, celebrato nel 330: la sconfitta costò a Eschine l'esilio."),
    "tlg0032.tlg001": (-358, "circa", "la narrazione si chiude con Mantinea (362); redazione a strati, pubblicazione negli ann…"),
    "tlg0032.tlg002": (-371, "circa", "replica all'accusa di Policrate (c. 393) con redazione protratta; pubblicazione comunem…"),
    "tlg0032.tlg003": (-363, "fase", "nessuna data; il quadro agrario riflette l'esperienza di Scillunte e l'opera si accompa…"),
    "tlg0032.tlg004": (-368, "fase", "nessuna data; dialogo socratico della maturità di Scillunte, nel gruppo con Economico e…"),
    "tlg0032.tlg005": (-385, "fase", "nessuna data; successiva all'Apologia platonica e affine al nucleo socratico che conflu…"),
    "tlg0032.tlg006": (-380, "circa", "pubblicata sotto il nome di Temistogene di Siracusa e già citata da Elleniche III,1,2: …"),
    "tlg0032.tlg007": (-361, "circa", "l'epilogo VIII,8 descrive una Persia decaduta quale appare dopo la rivolta dei satrapi …"),
    "tlg0032.tlg008": (-365, "fase", "nessuna data; dialogo sulla tirannide collocato nella fase matura, vicino al gruppo soc…"),
    "tlg0032.tlg009": (-359, "circa", "encomio funebre composto subito dopo la morte di Agesilao (360/359)"),
    "tlg0032.tlg010": (-387, "fase", "nessuna data; la Sparta descritta è ancora quella egemone, il che colloca l'opuscolo ne…"),
    "tlg0032.tlg011": (-355, "circa", "propone rimedi alle finanze di Atene all'indomani della guerra sociale (357-355): ultim…"),
    "tlg0032.tlg012": (-356, "fase", "nessuna data; scritto tecnico del gruppo ateniese finale, affiancato ai Poroi nella ric…"),
    "tlg0032.tlg013": (-362, "fase", "nessuna data; trattato equestre che l'Ipparchico presuppone, quindi anteriore agli scri…"),
    "tlg0032.tlg014": (-390, "fase", "nessuna data e proemio di autenticità discussa; nella cronologia relativa senofontea (D…"),
    "tlg0033.tlg001": (-476, "fase", "libro coestensivo all'intera attività (498-446): l'anno non data il libro ma riproduce …"),
    "tlg0033.tlg002": (-475, "fase", "raccolta che va dalla Pitica 10 (498) alla Pitica 8 (446): l'anno riproduce la posizion…"),
    "tlg0033.tlg003": (-474, "fase", "raccolta non databile in blocco (odi fra gli anni Ottanta e gli anni Quaranta): l'anno …"),
    "tlg0033.tlg004": (-473, "fase", "raccolta che comprende odi dal 478 (Istmica 8) alla metà del secolo: l'anno segna la qu…"),
    "tlg0059.tlg001": (-394, "fase", "Nessuna data: numero d'ordine nella fase giovanile socratica (dialoghi aporetici brevi)…"),
    "tlg0059.tlg002": (-396, "circa", "La critica converge sui primissimi anni dopo il processo e la morte di Socrate (399): c…"),
    "tlg0059.tlg003": (-395, "fase", "Nessuna data: ordine relativo nella fase giovanile, subito dopo l'Apologia secondo la s…"),
    "tlg0059.tlg004": (-382, "fase", "Nessuna data: collocato per stilometria all'inizio della fase matura, insieme a Menone …"),
    "tlg0059.tlg005": (-384, "fase", "Nessuna data: dialogo di transizione fra fase giovanile e matura nella cronologia relat…"),
    "tlg0059.tlg006": (-369, "circa", "Il proemio allude a Teeteto ferito nella battaglia presso Corinto, identificata dai più…"),
    "tlg0059.tlg007": (-365, "fase", "Nessuna data: primo numero d'ordine della fase tarda; la trilogia annunciata Teeteto-So…"),
    "tlg0059.tlg008": (-364, "fase", "Nessuna data: segue immediatamente il Sofista per rinvio interno esplicito, entro i dia…"),
    "tlg0059.tlg009": (-370, "fase", "Nessuna data: chiude la fase matura come autocritica della teoria delle idee e precede …"),
    "tlg0059.tlg010": (-358, "fase", "Nessuna data: fase tarda, dopo il gruppo dialettico Sofista-Politico e prima del Timeo,…"),
    "tlg0059.tlg011": (-380, "circa", "Il discorso di Aristofane allude al dioikismos spartano di Mantinea (385): terminus pos…"),
    "tlg0059.tlg012": (-372, "fase", "Nessuna data: fase matura avanzata, dopo Simposio e Repubblica, prima del gruppo Parmen…"),
    "tlg0059.tlg013": (-387, "fase", "Autenticità discussa: la tradizione antica ne fa il dialogo introduttivo alla filosofia…"),
    "tlg0059.tlg014": (-343, "fase", "Ritenuto spurio dalla critica moderna, ma tramandato nel corpus: collocato con gli altr…"),
    "tlg0059.tlg015": (-341, "fase", "Spurio secondo il consenso moderno, conservato nel corpus trasilleo: numero d'ordine ne…"),
    "tlg0059.tlg016": (-340, "fase", "Spurio secondo il consenso moderno, tramandato nel corpus: numero d'ordine nel gruppo d…"),
    "tlg0059.tlg017": (-342, "fase", "Spurio secondo il consenso moderno, tramandato nel corpus: numero d'ordine nel gruppo d…"),
    "tlg0059.tlg018": (-393, "fase", "Nessuna data: numero d'ordine nella fase giovanile socratica, gruppo dei dialoghi defin…"),
    "tlg0059.tlg019": (-397, "fase", "Nessuna data: fra i primi della fase giovanile socratica per brevità, struttura definit…"),
    "tlg0059.tlg020": (-392, "fase", "Nessuna data: fase giovanile socratica, gruppo definitorio-aporetico, subito dopo Carmi…"),
    "tlg0059.tlg021": (-388, "fase", "Nessuna data: ultima parte della fase giovanile, insieme ai dialoghi antisofistici magg…"),
    "tlg0059.tlg022": (-391, "fase", "Nessuna data: fase giovanile avanzata, gruppo antisofistico; la critica lo pone poco pr…"),
    "tlg0059.tlg023": (-390, "fase", "Nessuna data: chiude la fase giovanile e apre alla svolta politico-etica; posto dopo il…"),
    "tlg0059.tlg024": (-385, "fase", "Nessuna data: dialogo-cerniera fra fase giovanile e matura (prima comparsa dell'anamnes…"),
    "tlg0059.tlg025": (-389, "fase", "Autenticità talvolta discussa ma tramandato come platonico: collocato nella fase giovan…"),
    "tlg0059.tlg026": (-398, "fase", "Nessuna data: fra i primissimi della fase giovanile per brevità e schema elenctico; Ari…"),
    "tlg0059.tlg027": (-399, "fase", "Nessuna data: apre convenzionalmente la fase giovanile, essendo il piu breve e semplice…"),
    "tlg0059.tlg028": (-386, "circa", "L'orazione funebre arriva fino alla pace di Antalcida (387/386), anacronismo deliberato…"),
    "tlg0059.tlg029": (-376, "fase", "Autenticità discussa: la tetralogia trasillea lo pone immediatamente prima della Repubb…"),
    "tlg0059.tlg030": (-375, "circa", "Nessun appiglio esterno, ma la critica converge sul decennio 380-370, dopo la fondazion…"),
    "tlg0059.tlg031": (-356, "fase", "Nessuna data: fase tarda, dopo il Filebo per stilometria; il proemio lo lega alla Repub…"),
    "tlg0059.tlg032": (-355, "fase", "Nessuna data: segue il Timeo come suo seguito dichiarato ed è rimasto incompiuto; ordin…"),
    "tlg0059.tlg033": (-339, "fase", "Spurio secondo il consenso moderno; la tradizione lo tramanda come proemio alle Leggi, …"),
    "tlg0059.tlg034": (-347, "circa", "Opera dell'ultima vecchiaia, lasciata incompiuta alla morte di Platone (348/347) e pubb…"),
    "tlg0059.tlg035": (-345, "fase", "Attribuito già dall'antichità a Filippo di Opunte, editore delle Leggi, di cui è append…"),
    "tlg0059.tlg036": (-353, "circa", "Raccolta non omogenea e in gran parte sospetta; la VII, la piu discussa e la piu difesa…"),
    "tlg0085.tlg001": (-463, "circa", "P.Oxy. 2256 fr. 3 (didascalia mutila) sposta la Danaide dagli anni 490 al decennio 466-…"),
    "tlg0085.tlg002": (-472, "certa", "didascalia: Dionisie del 472, tetralogia Fineo-Persiani-Glauco Potnieo-Prometeo pirkaeu…"),
    "tlg0085.tlg003": (-456, "fase", "nessuna didascalia e paternita contestata (lingua, metrica e tecnica drammatica fanno p…"),
    "tlg0085.tlg004": (-467, "certa", "didascalia: Dionisie del 467, tetralogia tebana Laio-Edipo-Sette-Sfinge, primo premio"),
    "tlg0085.tlg005": (-458, "certa", "didascalia: Orestea alle Dionisie del 458, primo premio; Agamennone e la prima tragedia…"),
    "tlg0085.tlg006": (-458, "certa", "didascalia: Orestea alle Dionisie del 458; Coefore e la seconda tragedia della trilogia"),
    "tlg0085.tlg007": (-458, "certa", "didascalia: Orestea alle Dionisie del 458; Eumenidi e la terza tragedia della trilogia …"),
    "tlg0086.tlg003": (-328, "circa", "unico testo del corpus con appigli esterni: la descrizione delle magistrature registra …"),
    "tlg0086.tlg009": (-343, "fase", "nessuna data: l'anno e' numero d'ordine nella cronologia relativa del corpus, che asseg…"),
    "tlg0086.tlg010": (-332, "fase", "nessuna data: nella cronologia relativa segue l'Etica Eudemia e prepara la Politica, ch…"),
    "tlg0086.tlg025": (-325, "fase", "nessuna data: raccolta stratificata di trattati distinti, riuniti e ordinati postumi da…"),
    "tlg0086.tlg029": (-320, "fase", "opera spuria tramandata sotto il nome di Aristotele: il libro II riflette la finanza de…"),
    "tlg0086.tlg034": (-335, "fase", "nessuna data: nota di scuola legata all'insegnamento del Liceo, fondato nel 335; l'anno…"),
    "tlg0086.tlg035": (-330, "fase", "nessuna data e composizione per blocchi non omogenei: l'anno la ordina dopo l'Etica Nic…"),
    "tlg0086.tlg038": (-338, "fase", "nessuna data unitaria: nuclei risalenti all'insegnamento accademico anteriore al 347, m…"),
    "tlg0086.tlg045": (-318, "fase", "opuscolo spurio, di ambiente peripatetico-eclettico che la critica riferisce al I secol…"),
    "tlg0199.tlg001": (-468, "fase", "raccolta scaglionata fra l'ode 13 (c. 485) e le odi 6-7 per Liace (452): l'anno-ancora …"),
    "tlg0199.tlg002": (-465, "fase", "nessuno dei ditirambi è databile; l'anno li colloca nella fase egea e ateniese della ca…"),
    "tlg0533.tlg003": (-248, "fase", "nessuna data: raccolta sparsa (epitafio del padre, epigramma per Eraclito) composta lun…"),
    "tlg0533.tlg004": (-245, "fase", "nessuna data: secondo gruppo di epigrammi tramandato separatamente, con pezzi di attrib…"),
    "tlg0533.tlg015": (-281, "circa", "l'elogio del sovrano giovane che tutto compie in un giorno e' riferito all'ascesa di To…"),
    "tlg0533.tlg016": (-250, "fase", "datazione realmente contesa: chi lo lega al ritorno di Cirene sotto l'Egitto e alla cas…"),
    "tlg0533.tlg017": (-276, "fase", "nessun aggancio storico interno; l'anno e' numero d'ordine dentro la successione relati…"),
    "tlg0533.tlg018": (-273, "circa", "terminus post quem sicuro: la profezia di Apollo (vv. 171-187) allude alla rivolta dei …"),
    "tlg0533.tlg019": (-270, "fase", "nessuna data: inno mimetico in distici e dialetto dorico, privo di appigli storici; l'a…"),
    "tlg0533.tlg020": (-268, "fase", "nessuna data: secondo inno mimetico, gemello dei Lavacri per forma e dialetto; l'anno l…"),
    "tlg0540.tlg001": (-400, "fase", "Senza appigli cronologici interni: presuppone la democrazia restaurata (post 403); coll…"),
    "tlg0540.tlg002": (-392, "circa", "Epitafio per i caduti ateniesi accorsi in aiuto a Corinto: guerra corinzia, la critica …"),
    "tlg0540.tlg003": (-393, "circa", "Il discorso richiama la battaglia di Corinto (394) come fatto recente: 393 o poco dopo."),
    "tlg0540.tlg004": (-395, "fase", "Nessun dato interno databile; numero d'ordine dentro il gruppo delle apologie post-403."),
    "tlg0540.tlg005": (-398, "fase", "Conservata frammentaria e priva di riferimenti databili: solo ordine relativo tra le ap…"),
    "tlg0540.tlg006": (-399, "circa", "Requisitoria per il processo di empietà ad Andocide, 400/399; la paternità lisiana è du…"),
    "tlg0540.tlg007": (-395, "circa", "Il locatario entra in possesso del fondo nel 397/6 e da lì si contano gli anni: 396 o p…"),
    "tlg0540.tlg008": (-380, "fase", "Estranea al corpus giudiziario e ritenuta spuria: collocata convenzionalmente tra gli s…"),
    "tlg0540.tlg009": (-393, "fase", "Databile solo entro l'arco della guerra corinzia (395-387), senza convergenza su un anno."),
    "tlg0540.tlg010": (-384, "certa", "L'oratore calcola vent'anni dal ritorno dal Pireo (403): dibattimento del 384/3."),
    "tlg0540.tlg011": (-384, "circa", "Epitome antica dell'or. 10: rinvia allo stesso processo del 384/3."),
    "tlg0540.tlg012": (-403, "certa", "Pronunciata da Lisia stesso alle euthynai di Eratostene, subito dopo la caduta dei Tren…"),
    "tlg0540.tlg013": (-399, "circa", "Processo per endeixis contro Agorato dopo l'amnistia: la critica converge sul 399."),
    "tlg0540.tlg014": (-395, "certa", "Processo ad Alcibiade il Giovane per diserzione dopo la campagna di Aliarto (395)."),
    "tlg0540.tlg015": (-395, "circa", "Seconda accusa nello stesso processo del 395; alcuni la ritengono esercitazione posteri…"),
    "tlg0540.tlg016": (-392, "circa", "Dokimasia di Mantiteo: i riferimenti alle campagne della guerra corinzia portano al 392…"),
    "tlg0540.tlg017": (-397, "circa", "La vertenza col fisco sui beni di Eratone si colloca nel 397 secondo il computo degli a…"),
    "tlg0540.tlg018": (-396, "circa", "La richiesta di restituzione dei beni confiscati segue di poco la restaurazione: 396 pe…"),
    "tlg0540.tlg019": (-387, "circa", "Il fallimento della missione presso Evagora di Cipro è il termine post quem: 388/7."),
    "tlg0540.tlg020": (-410, "circa", "Difesa di Polistrato dopo la caduta dei Quattrocento (411): 410 ca.; paternità lisiana …"),
    "tlg0540.tlg021": (-402, "circa", "La prova addotta e' materialmente falsa: il catalogo di liturgie non si chiude col 404/…"),
    "tlg0540.tlg022": (-386, "circa", "La crisi granaria e il ruolo dei sitophylakes portano la critica al 386."),
    "tlg0540.tlg023": (-400, "fase", "Priva di indizi sicuri: si ipotizza il 400/399 dai riferimenti agli esuli plateesi, ma …"),
    "tlg0540.tlg024": (-402, "fase", "Nessuna data ricavabile: posteriore al 403, collocata per ordine all'inizio della fase …"),
    "tlg0540.tlg025": (-400, "circa", "Difesa dall'accusa di complicità con i Trenta, subito dopo l'amnistia: 401-399."),
    "tlg0540.tlg026": (-382, "certa", "Dokimasia di Evandro candidato all'arcontato del 382/1."),
    "tlg0540.tlg027": (-390, "circa", "Epilogo del processo agli ambasciatori guidati da Epicrate: la critica converge sul 390."),
    "tlg0540.tlg028": (-388, "circa", "Processo a Ergocle, luogotenente di Trasibulo, dopo la morte di questi (389): 388."),
    "tlg0540.tlg029": (-388, "circa", "Segue immediatamente la condanna di Ergocle, contro il suo tesoriere: stesso anno o poc…"),
    "tlg0540.tlg030": (-399, "circa", "Euthynai di Nicomaco al termine della revisione delle leggi (410-400): 399."),
    "tlg0540.tlg031": (-400, "fase", "Dokimasia di Filone collocabile solo tra il 403 e il 398: nessuna convergenza su un ann…"),
    "tlg0540.tlg032": (-400, "circa", "La tutela contestata si chiude con la maggiore età dei pupilli: processo del 400 ca."),
    "tlg0540.tlg033": (-388, "circa", "Discorso all'Olimpiade davanti agli inviati di Dionigi I: Ol. 98 (388), secondo altri O…"),
    "tlg0540.tlg034": (-403, "certa", "Intervento nel dibattito sulla proposta di Formisio, subito dopo la restaurazione democ…"),
    "tlg0543.tlg001": (-145, "circa", "iniziata durante l'ostaggio romano dopo il 167 e ampliata a quarant'anni dopo il 146, c…"),
}


def data_per(work_id):
    """(anno, tipo, base) oppure None se l'opera non è stata datata."""
    return DATE.get(work_id)
